<a href="https://colab.research.google.com/github/bchaithanyasai/PredictLateArrivalsPaper/blob/master/Data_Preprocessing_and_Feature_Engineering_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install httplib2==0.15.0

Requirement already satisfied: httplib2==0.15.0 in /usr/local/lib/python3.6/dist-packages (0.15.0)

In [2]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

In [0]:
X_columns=['YEAR','MONTH','DAY','DAY_OF_WEEK', 'AIRLINE', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT','SCHEDULED_DEPARTURE',
           'DEPARTURE_TIME','DEPARTURE_DELAY', 'TAXI_OUT','WHEELS_OFF','SCHEDULED_TIME','SCHEDULED_ARRIVAL','DISTANCE','AIR_TIME','DIVERTED',
           'AIR_SYSTEM_DELAY','SECURITY_DELAY','AIRLINE_DELAY','LATE_AIRCRAFT_DELAY','WEATHER_DELAY','AIR_SYSTEM_DELAY_is_missing',
           'SECURITY_DELAY_is_missing','AIRLINE_DELAY_is_missing','LATE_AIRCRAFT_DELAY_is_missing','WEATHER_DELAY_is_missing']

In [0]:
import pandas as pd

data=pd.read_csv('/content/drive/My Drive/Handled_data_2019.csv')

In [5]:
data = data.assign(OUTCOME=(data['ARRIVAL_DELAY'] > 4).astype(int))
data

         YEAR  MONTH  ...  WEATHER_DELAY_is_missing  OUTCOME
0        2019      1  ...                         1        0
1        2019      1  ...                         1        0
2        2019      1  ...                         1        0
3        2019      1  ...                         1        0
4        2019      1  ...                         1        0
...       ...    ...  ...                       ...      ...
7266657  2019     12  ...                         0        1
7266658  2019     12  ...                         1        0
7266659  2019     12  ...                         1        0
7266660  2019     12  ...                         1        0
7266661  2019     12  ...                         1        0

[7266662 rows x 31 columns]

In [0]:
X=data[X_columns]
y=data['OUTCOME']

In [7]:
cat=pd.DataFrame()
cat['AIRLINE_ORIGIN_AIRPORT']=X['AIRLINE']+"_"+X['ORIGIN_AIRPORT']
cat['AIRLINE_DESTINATION_AIRPORT']=X['AIRLINE']+"_"+X['DESTINATION_AIRPORT']
cat['ORIGIN_AIRPORT_DESTINATION_AIRPORT']=X['ORIGIN_AIRPORT']+"_"+X['DESTINATION_AIRPORT']
cat

        AIRLINE_ORIGIN_AIRPORT  ... ORIGIN_AIRPORT_DESTINATION_AIRPORT
0                       9E_ATL  ...                            ATL_CSG
1                       9E_ATL  ...                            ATL_CSG
2                       9E_ATL  ...                            ATL_CSG
3                       9E_ATL  ...                            ATL_CSG
4                       9E_ATL  ...                            ATL_CSG
...                        ...  ...                                ...
7266657                 B6_MCO  ...                            MCO_SWF
7266658                 B6_DCA  ...                            DCA_BOS
7266659                 B6_PHL  ...                            PHL_BOS
7266660                 B6_BOS  ...                            BOS_SJU
7266661                 B6_SJU  ...                            SJU_BOS

[7266662 rows x 3 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder

cat_features = ['AIRLINE_ORIGIN_AIRPORT','AIRLINE_DESTINATION_AIRPORT','ORIGIN_AIRPORT_DESTINATION_AIRPORT']
encoder = LabelEncoder()

# Apply the label encoder to each column
cat = cat[cat_features].apply(encoder.fit_transform)
cat.head(10)

   AIRLINE_ORIGIN_AIRPORT  ...  ORIGIN_AIRPORT_DESTINATION_AIRPORT
0                       5  ...                                 178
1                       5  ...                                 178
2                       5  ...                                 178
3                       5  ...                                 178
4                       5  ...                                 178
5                       5  ...                                 178
6                       5  ...                                 178
7                       5  ...                                 178
8                       5  ...                                 178
9                       5  ...                                 178

[10 rows x 3 columns]

In [0]:
X=X.join(cat)

In [10]:
X

         YEAR  ...  ORIGIN_AIRPORT_DESTINATION_AIRPORT
0        2019  ...                                 178
1        2019  ...                                 178
2        2019  ...                                 178
3        2019  ...                                 178
4        2019  ...                                 178
...       ...  ...                                 ...
7266657  2019  ...                                3645
7266658  2019  ...                                1393
7266659  2019  ...                                4747
7266660  2019  ...                                 713
7266661  2019  ...                                5891

[7266662 rows x 30 columns]

In [0]:
from numpy import array

data=X[['AIRLINE']]
data=array(data)
data

array([['AS'],
       ['AA'],
       ['US'],
       ...,
       ['B6'],
       ['B6'],
       ['B6']], dtype=object)

In [0]:
# importing one hot encoder from sklearn 
from sklearn.preprocessing import OneHotEncoder 

# creating one hot encoder object with categorical feature 0 
# indicating the first column 
onehotencoder = OneHotEncoder()
data = onehotencoder.fit_transform(data)
data

<5714008x14 sparse matrix of type '<class 'numpy.float64'>'
	with 5714008 stored elements in Compressed Sparse Row format>

In [0]:
data=pd.DataFrame(data.toarray())
data

           0    1    2    3    4    5    6    7    8    9   10   11   12   13
0        0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1        1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
3        1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4        0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
5714003  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5714004  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5714005  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5714006  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5714007  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5714008 rows x 14 columns]

In [11]:
data=pd.get_dummies(X['AIRLINE'])
data

         9E  AA  AS  B6  DL  EV  F9  G4  HA  MQ  NK  OH  OO  UA  WN  YV  YX
0         1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
1         1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
2         1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
3         1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
4         1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
...      ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
7266657   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
7266658   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
7266659   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
7266660   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
7266661   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0

[7266662 rows x 17 columns]

In [12]:
X=X.join(data)
X.drop(['AIRLINE'],axis=1,inplace=True)
X

         YEAR  MONTH  DAY  DAY_OF_WEEK ORIGIN_AIRPORT  ... OO  UA  WN  YV  YX
0        2019      1    6            7            ATL  ...  0   0   0   0   0
1        2019      1    7            1            ATL  ...  0   0   0   0   0
2        2019      1    8            2            ATL  ...  0   0   0   0   0
3        2019      1    9            3            ATL  ...  0   0   0   0   0
4        2019      1   10            4            ATL  ...  0   0   0   0   0
...       ...    ...  ...          ...            ...  ... ..  ..  ..  ..  ..
7266657  2019     12   31            2            MCO  ...  0   0   0   0   0
7266658  2019     12   31            2            DCA  ...  0   0   0   0   0
7266659  2019     12   31            2            PHL  ...  0   0   0   0   0
7266660  2019     12   31            2            BOS  ...  0   0   0   0   0
7266661  2019     12   31            2            SJU  ...  0   0   0   0   0

[7266662 rows x 46 columns]

In [13]:
import datetime

def format_heure(time):
    if pd.isnull(time):
        return np.nan
    else:
        if time == 2400: time = 0
        time = "{0:04d}".format(int(time))
        heure = datetime.time(int(time[0:2]), int(time[2:4]))
        return heure

X['converted_DEPARTURE_TIME'] = X['DEPARTURE_TIME'].apply(format_heure)
X['converted_SCHEDULED_DEPARTURE'] = X['SCHEDULED_DEPARTURE'].apply(format_heure)
X['converted_SCHEDULED_ARRIVAL'] = X['SCHEDULED_ARRIVAL'].apply(format_heure)
X['converted_WHEELS_OFF'] = X['WHEELS_OFF'].apply(format_heure)
X

         YEAR  MONTH  ...  converted_SCHEDULED_ARRIVAL  converted_WHEELS_OFF
0        2019      1  ...                     17:32:00              17:00:00
1        2019      1  ...                     17:32:00              16:50:00
2        2019      1  ...                     17:32:00              16:58:00
3        2019      1  ...                     17:32:00              16:54:00
4        2019      1  ...                     17:32:00              16:56:00
...       ...    ...  ...                          ...                   ...
7266657  2019     12  ...                     16:39:00              15:20:00
7266658  2019     12  ...                     15:50:00              14:29:00
7266659  2019     12  ...                     08:25:00              07:04:00
7266660  2019     12  ...                     13:15:00              08:22:00
7266661  2019     12  ...                     07:38:00              04:41:00

[7266662 rows x 50 columns]

In [14]:
X['converted_DEPARTURE_TIME']=[i.strftime("%H:%M:%S") for i in X.converted_DEPARTURE_TIME]
X['DEPARTURE_TIME_HOUR']=[i.partition(':')[0] for i in X.converted_DEPARTURE_TIME]
X['DEPARTURE_TIME_MINUTE']=[i.partition(':')[2].partition(":")[0] for i in X.converted_DEPARTURE_TIME]

X['converted_SCHEDULED_DEPARTURE']=[i.strftime("%H:%M:%S") for i in X.converted_SCHEDULED_DEPARTURE]
X['SCHEDULED_DEPARTURE_HOUR']=[i.partition(':')[0] for i in X.converted_SCHEDULED_DEPARTURE]
X['SCHEDULED_DEPARTURE_MINUTE']=[i.partition(':')[2].partition(":")[0] for i in X.converted_SCHEDULED_DEPARTURE]

X['converted_SCHEDULED_ARRIVAL']=[i.strftime("%H:%M:%S") for i in X.converted_SCHEDULED_ARRIVAL]
X['SCHEDULED_ARRIVAL_HOUR']=[i.partition(':')[0] for i in X.converted_SCHEDULED_ARRIVAL]
X['SCHEDULED_ARRIVAL_MINUTE']=[i.partition(':')[2].partition(":")[0] for i in X.converted_SCHEDULED_ARRIVAL]

X['converted_WHEELS_OFF']=[i.strftime("%H:%M:%S") for i in X.converted_WHEELS_OFF]
X['WHEELS_OFF_HOUR']=[i.partition(':')[0] for i in X.converted_WHEELS_OFF]
X['WHEELS_OFF_MINUTE']=[i.partition(':')[2].partition(":")[0] for i in X.converted_WHEELS_OFF]

X

         YEAR  MONTH  ...  WHEELS_OFF_HOUR  WHEELS_OFF_MINUTE
0        2019      1  ...               17                 00
1        2019      1  ...               16                 50
2        2019      1  ...               16                 58
3        2019      1  ...               16                 54
4        2019      1  ...               16                 56
...       ...    ...  ...              ...                ...
7266657  2019     12  ...               15                 20
7266658  2019     12  ...               14                 29
7266659  2019     12  ...               07                 04
7266660  2019     12  ...               08                 22
7266661  2019     12  ...               04                 41

[7266662 rows x 58 columns]

In [0]:
import numpy as np
import pandas as pd

df={"hr":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,0],
    "mnth":[1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12]}
df=pd.DataFrame(df)

df['hr_sin'] = np.sin(df.hr*(2.*np.pi/24))
df['hr_cos'] = np.cos(df.hr*(2.*np.pi/24))
df['chr_sin'] = np.sin(df.hr*((2.*np.pi)/24))
df['chr_cos'] = np.cos(df.hr*((2.*np.pi)/24))
df['mnth_sin'] = np.sin((df.mnth-1)*(2.*np.pi/12))
df['mnth_cos'] = np.cos((df.mnth-1)*(2.*np.pi/12))
df

    hr  mnth        hr_sin  ...       chr_cos      mnth_sin      mnth_cos
0    1     1  2.588190e-01  ...  9.659258e-01  0.000000e+00  1.000000e+00
1    2     2  5.000000e-01  ...  8.660254e-01  5.000000e-01  8.660254e-01
2    3     3  7.071068e-01  ...  7.071068e-01  8.660254e-01  5.000000e-01
3    4     4  8.660254e-01  ...  5.000000e-01  1.000000e+00  6.123234e-17
4    5     5  9.659258e-01  ...  2.588190e-01  8.660254e-01 -5.000000e-01
5    6     6  1.000000e+00  ...  6.123234e-17  5.000000e-01 -8.660254e-01
6    7     7  9.659258e-01  ... -2.588190e-01  1.224647e-16 -1.000000e+00
7    8     8  8.660254e-01  ... -5.000000e-01 -5.000000e-01 -8.660254e-01
8    9     9  7.071068e-01  ... -7.071068e-01 -8.660254e-01 -5.000000e-01
9   10    10  5.000000e-01  ... -8.660254e-01 -1.000000e+00 -1.836970e-16
10  11    11  2.588190e-01  ... -9.659258e-01 -8.660254e-01  5.000000e-01
11  12    12  1.224647e-16  ... -1.000000e+00 -5.000000e-01  8.660254e-01
12  13     1 -2.588190e-01  ... -9.659258e-01  0.000000e+00  1.000000e+00
13  14     2 -5.000000e-01  ... -8.660254e-01  5.000000e-01  8.660254e-01
14  15     3 -7.071068e-01  ... -7.071068e-01  8.660254e-01  5.000000e-01
15  16     4 -8.660254e-01  ... -5.000000e-01  1.000000e+00  6.123234e-17
16  17     5 -9.659258e-01  ... -2.588190e-01  8.660254e-01 -5.000000e-01
17  18     6 -1.000000e+00  ... -1.836970e-16  5.000000e-01 -8.660254e-01
18  19     7 -9.659258e-01  ...  2.588190e-01  1.224647e-16 -1.000000e+00
19  20     8 -8.660254e-01  ...  5.000000e-01 -5.000000e-01 -8.660254e-01
20  21     9 -7.071068e-01  ...  7.071068e-01 -8.660254e-01 -5.000000e-01
21  22    10 -5.000000e-01  ...  8.660254e-01 -1.000000e+00 -1.836970e-16
22  23    11 -2.588190e-01  ...  9.659258e-01 -8.660254e-01  5.000000e-01
23   0    12  0.000000e+00  ...  1.000000e+00 -5.000000e-01  8.660254e-01

[24 rows x 8 columns]

In [15]:
X['DEPARTURE_TIME_HOUR']=X['DEPARTURE_TIME_HOUR'].astype(int)
X['DEPARTURE_TIME_MINUTE']=X['DEPARTURE_TIME_MINUTE'].astype(int)
X['SCHEDULED_DEPARTURE_HOUR']=X['SCHEDULED_DEPARTURE_HOUR'].astype(int)
X['SCHEDULED_DEPARTURE_MINUTE']=X['SCHEDULED_DEPARTURE_MINUTE'].astype(int)
X['SCHEDULED_ARRIVAL_HOUR']=X['SCHEDULED_ARRIVAL_HOUR'].astype(int)
X['SCHEDULED_ARRIVAL_MINUTE']=X['SCHEDULED_ARRIVAL_MINUTE'].astype(int)
X['WHEELS_OFF_HOUR']=X['WHEELS_OFF_HOUR'].astype(int)
X['WHEELS_OFF_MINUTE']=X['WHEELS_OFF_MINUTE'].astype(int)
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7266662 entries, 0 to 7266661
Data columns (total 58 columns):
 #   Column                              Dtype
---  ------                              -----
 0   YEAR                                int64
 1   MONTH                               int64
 2   DAY                                 int64
 3   DAY_OF_WEEK                         int64
 4   ORIGIN_AIRPORT                      object
 5   DESTINATION_AIRPORT                 object
 6   SCHEDULED_DEPARTURE                 int64
 7   DEPARTURE_TIME                      float64
 8   DEPARTURE_DELAY                     float64
 9   TAXI_OUT                            float64
 10  WHEELS_OFF                          float64
 11  SCHEDULED_TIME                      float64
 12  SCHEDULED_ARRIVAL                   int64
 13  DISTANCE                            float64
 14  AIR_TIME                            float64
 15  DIVERTED                            float64
 16  AIR_SYSTEM_DELAY                    float64
 17  SECURITY_DELAY                      float64
 18  AIRLINE_DELAY                       float64
 19  LATE_AIRCRAFT_DELAY                 float64
 20  WEATHER_DELAY                       float64
 21  AIR_SYSTEM_DELAY_is_missing         int64
 22  SECURITY_DELAY_is_missing           int64
 23  AIRLINE_DELAY_is_missing            int64
 24  LATE_AIRCRAFT_DELAY_is_missing      int64
 25  WEATHER_DELAY_is_missing            int64
 26  AIRLINE_ORIGIN_AIRPORT              int64
 27  AIRLINE_DESTINATION_AIRPORT         int64
 28  ORIGIN_AIRPORT_DESTINATION_AIRPORT  int64
 29  9E                                  uint8
 30  AA                                  uint8
 31  AS                                  uint8
 32  B6                                  uint8
 33  DL                                  uint8
 34  EV                                  uint8
 35  F9                                  uint8
 36  G4                                  uint8
 37  HA                                  uint8
 38  MQ                                  uint8
 39  NK                                  uint8
 40  OH                                  uint8
 41  OO                                  uint8
 42  UA                                  uint8
 43  WN                                  uint8
 44  YV                                  uint8
 45  YX                                  uint8
 46  converted_DEPARTURE_TIME            object
 47  converted_SCHEDULED_DEPARTURE       object
 48  converted_SCHEDULED_ARRIVAL         object
 49  converted_WHEELS_OFF                object
 50  DEPARTURE_TIME_HOUR                 int64
 51  DEPARTURE_TIME_MINUTE               int64
 52  SCHEDULED_DEPARTURE_HOUR            int64
 53  SCHEDULED_DEPARTURE_MINUTE          int64
 54  SCHEDULED_ARRIVAL_HOUR              int64
 55  SCHEDULED_ARRIVAL_MINUTE            int64
 56  WHEELS_OFF_HOUR                     int64
 57  WHEELS_OFF_MINUTE                   int64
dtypes: float64(13), int64(22), object(6), uint8(17)
memory usage: 2.3+ GB

In [0]:
import numpy as np
X['DEPARTURE_TIME_HOUR_sin'] = np.sin(X.DEPARTURE_TIME_HOUR*((2.*np.pi)/24))
X['DEPARTURE_TIME_HOUR_cos'] = np.cos(X.DEPARTURE_TIME_HOUR*((2.*np.pi)/24))
X['SCHEDULED_DEPARTURE_HOUR_sin'] = np.sin(X.SCHEDULED_DEPARTURE_HOUR*((2.*np.pi)/24))
X['SCHEDULED_DEPARTURE_HOUR_cos'] = np.cos(X.SCHEDULED_DEPARTURE_HOUR*((2.*np.pi)/24))
X['SCHEDULED_ARRIVAL_HOUR_sin'] = np.sin(X.SCHEDULED_ARRIVAL_HOUR*((2.*np.pi)/24))
X['SCHEDULED_ARRIVAL_HOUR_cos'] = np.cos(X.SCHEDULED_ARRIVAL_HOUR*((2.*np.pi)/24))

X['DEPARTURE_TIME_MINUTE_sin'] = np.sin(X.DEPARTURE_TIME_MINUTE*((2.*np.pi)/60))
X['DEPARTURE_TIME_MINUTE_cos'] = np.cos(X.DEPARTURE_TIME_MINUTE*((2.*np.pi)/60))
X['SCHEDULED_DEPARTURE_MINUTE_sin'] = np.sin(X.SCHEDULED_DEPARTURE_MINUTE*((2.*np.pi)/60))
X['SCHEDULED_DEPARTURE_MINUTE_cos'] = np.cos(X.SCHEDULED_DEPARTURE_MINUTE*((2.*np.pi)/60))
X['SCHEDULED_ARRIVAL_MINUTE_sin'] = np.sin(X.SCHEDULED_ARRIVAL_MINUTE*((2.*np.pi)/60))
X['SCHEDULED_ARRIVAL_MINUTE_cos'] = np.cos(X.SCHEDULED_ARRIVAL_MINUTE*((2.*np.pi)/60))

X['MONTH_sin'] = np.sin((X.MONTH-1)*(2.*np.pi/12))
X['MONTH_cos'] = np.cos((X.MONTH-1)*(2.*np.pi/12))

X['DAY_OF_WEEK_sin'] = np.sin((X.DAY_OF_WEEK-1)*(2.*np.pi/7))
X['DAY_OF_WEEK_cos'] = np.cos((X.DAY_OF_WEEK-1)*(2.*np.pi/7))

X

         YEAR  MONTH  DAY  ...  MONTH_cos DAY_OF_WEEK_sin DAY_OF_WEEK_cos
0        2015      1    1  ...   1.000000        0.433884       -0.900969
1        2015      1    1  ...   1.000000        0.433884       -0.900969
2        2015      1    1  ...   1.000000        0.433884       -0.900969
3        2015      1    1  ...   1.000000        0.433884       -0.900969
4        2015      1    1  ...   1.000000        0.433884       -0.900969
...       ...    ...  ...  ...        ...             ...             ...
5714003  2015     12   31  ...   0.866025        0.433884       -0.900969
5714004  2015     12   31  ...   0.866025        0.433884       -0.900969
5714005  2015     12   31  ...   0.866025        0.433884       -0.900969
5714006  2015     12   31  ...   0.866025        0.433884       -0.900969
5714007  2015     12   31  ...   0.866025        0.433884       -0.900969

[5714008 rows x 68 columns]

In [16]:
y=pd.DataFrame(y)
y

         OUTCOME
0              0
1              0
2              0
3              0
4              0
...          ...
7266657        1
7266658        0
7266659        0
7266660        0
7266661        0

[7266662 rows x 1 columns]

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.25,random_state=27)

In [18]:
for each in [Y_train,Y_test]:
    print(f"Outcome fraction = {each.OUTCOME.mean():.4f}")

Outcome fraction = 0.2841
Outcome fraction = 0.2844

In [19]:
data=X_train.join(Y_train)
data

         YEAR  MONTH  DAY  ...  WHEELS_OFF_HOUR WHEELS_OFF_MINUTE OUTCOME
985289   2019      2   17  ...               17                 1       0
5243685  2019      9    4  ...               11                56       1
1604102  2019      3    3  ...               20                 3       1
3196153  2019      6   17  ...               17                27       1
1910817  2019      4   10  ...                8                48       1
...       ...    ...  ...  ...              ...               ...     ...
4985584  2019      9    3  ...                6                50       0
4390712  2019      7   24  ...               12                19       0
3684895  2019      7   19  ...               18                50       0
560968   2019      1   22  ...                5                55       0
1429176  2019      3    1  ...               15                19       1

[5449996 rows x 59 columns]

In [20]:
ori_airport_means=data.groupby('ORIGIN_AIRPORT')['OUTCOME'].mean()
ori_airport_means

ORIGIN_AIRPORT
ABE    0.279620
ABI    0.279167
ABQ    0.254959
ABR    0.199650
ABY    0.207827
         ...
WYS    0.162562
XNA    0.287077
XWA    0.361842
YAK    0.203488
YUM    0.208976
Name: OUTCOME, Length: 360, dtype: float64

In [21]:
ori_di=dict(ori_airport_means)
ori_di

{'ABE': 0.2796195652173913,
 'ABI': 0.2791666666666667,
 'ABQ': 0.25495929365898407,
 'ABR': 0.19964973730297722,
 'ABY': 0.2078272604588394,
 'ACK': 0.3308913308913309,
 'ACT': 0.2545027407987471,
 'ACV': 0.33783783783783783,
 'ACY': 0.192573402417962,
 'ADK': 0.4177215189873418,
 'ADQ': 0.2743362831858407,
 'AEX': 0.2810126582278481,
 'AGS': 0.2546230440967283,
 'AKN': 0.15254237288135594,
 'ALB': 0.25444238526109236,
 'ALO': 0.2768361581920904,
 'AMA': 0.2629083245521602,
 'ANC': 0.20370632338378838,
 'APN': 0.2267818574514039,
 'ART': 0.30201342281879195,
 'ASE': 0.38877931185623493,
 'ATL': 0.24681533542409415,
 'ATW': 0.2910518053375196,
 'ATY': 0.25268817204301075,
 'AUS': 0.2702740944372574,
 'AVL': 0.2791791363830697,
 'AVP': 0.22661596958174904,
 'AZA': 0.33505033949894636,
 'AZO': 0.25925925925925924,
 'BDL': 0.23888285052691272,
 'BET': 0.2725694444444444,
 'BFF': 0.20575221238938052,
 'BFL': 0.18262806236080179,
 'BFM': 0.46226415094339623,
 'BGM': 0.2145985401459854,
 'BGR': 0.295144157814871,
 'BHM': 0.27868165630891695,
 'BIL': 0.23590746171391333,
 'BIS': 0.25112395632626844,
 'BJI': 0.16576576576576577,
 'BKG': 0.31547619047619047,
 'BLI': 0.16618287373004353,
 'BLV': 0.39254658385093166,
 'BMI': 0.2616487455197133,
 'BNA': 0.2818150578455597,
 'BOI': 0.22738871562234195,
 'BOS': 0.296889529053549,
 'BPT': 0.2865013774104683,
 'BQK': 0.20806241872561768,
 'BQN': 0.3073341094295693,
 'BRD': 0.21961620469083157,
 'BRO': 0.21421319796954313,
 'BRW': 0.1878453038674033,
 'BTM': 0.14201183431952663,
 'BTR': 0.281272210376688,
 'BTV': 0.2951902368987796,
 'BUF': 0.24643471505465844,
 'BUR': 0.2550082386610008,
 'BWI': 0.27939525289187145,
 'BZN': 0.2871170463472113,
 'CAE': 0.2316538882803943,
 'CAK': 0.2692725298588491,
 'CDC': 0.21934369602763384,
 'CDV': 0.22242647058823528,
 'CGI': 0.2507163323782235,
 'CHA': 0.2394041769041769,
 'CHO': 0.29377064653138274,
 'CHS': 0.2462417954689816,
 'CID': 0.3061699650756694,
 'CIU': 0.22266401590457258,
 'CKB': 0.3328100470957614,
 'CLE': 0.248598956464125,
 'CLL': 0.18148375229920294,
 'CLT': 0.3116239820129123,
 'CMH': 0.24759950992962362,
 'CMI': 0.29980657640232106,
 'CMX': 0.3062015503875969,
 'CNY': 0.2780373831775701,
 'COD': 0.17994100294985252,
 'COS': 0.30424143556280586,
 'COU': 0.36379928315412186,
 'CPR': 0.17875647668393782,
 'CRP': 0.23136246786632392,
 'CRW': 0.29046153846153844,
 'CSG': 0.226890756302521,
 'CVG': 0.2771687187271603,
 'CWA': 0.22947253942359977,
 'CYS': 0.30662983425414364,
 'DAB': 0.20319541171650962,
 'DAL': 0.3067896060352054,
 'DAY': 0.27717605356439545,
 'DBQ': 0.2888283378746594,
 'DCA': 0.28687208878647324,
 'DEN': 0.3374506702369448,
 'DFW': 0.3480937197980364,
 'DHN': 0.2313649564375605,
 'DLG': 0.27586206896551724,
 'DLH': 0.25873544093178036,
 'DRO': 0.30782608695652175,
 'DRT': 0.1750465549348231,
 'DSM': 0.24943766066838047,
 'DTW': 0.2543613302371591,
 'DVL': 0.21739130434782608,
 'EAR': 0.1885245901639344,
 'EAU': 0.24554455445544554,
 'ECP': 0.21386460662736329,
 'EGE': 0.38259833134684146,
 'EKO': 0.103515625,
 'ELM': 0.18681318681318682,
 'ELP': 0.23291381233073125,
 'ERI': 0.2511574074074074,
 'ESC': 0.2727272727272727,
 'EUG': 0.27454068241469815,
 'EVV': 0.27505112474437626,
 'EWN': 0.1934745277618775,
 'EWR': 0.36319415070397004,
 'EYW': 0.26052198448154246,
 'FAI': 0.15962837837837837,
 'FAR': 0.29976851851851855,
 'FAT': 0.23989071038251367,
 'FAY': 0.2572062084257206,
 'FCA': 0.2146643109540636,
 'FLG': 0.1520991052993806,
 'FLL': 0.3139257185209586,
 'FNT': 0.259157148483655,
 'FSD': 0.30038535645472064,
 'FSM': 0.2496902106567534,
 'FWA': 0.26826923076923076,
 'GCC': 0.30018083182640143,
 'GCK': 0.27115384615384613,
 'GEG': 0.23943189443077612,
 'GFK': 0.19767441860465115,
 'GGG': 0.1880597014925373,
 'GJT': 0.19802306425041186,
 'GNV': 0.29006031995803827,
 'GPT': 0.26326774001192604,
 'GRB': 0.270042194092827,
 'GRI': 0.2908878504672897,
 'GRK': 0.2463191404695583,
 'GRR': 0.29030403220010065,
 'GSO': 0.2363991444248117,
 'GSP': 0.26173809117295543,
 'GST': 0.24242424242424243,
 'GTF': 0.17782738095238096,
 'GTR': 0.21460674157303372,
 'GUC': 0.33513513513513515,
 'GUM': 0.1888,
 'HDN': 0.3669950738916256,
 'HGR': 0.3617021276595745,
 'HHH': 0.34673979280926265,
 'HIB': 0.15711252653927812,
 'HLN': 0.20388349514563106,
 'HNL': 0.22886709120788826,
 'HOB': 0.27041742286751363,
 'HOU': 0.30099411737881343,
 'HPN': 0.30697509736811046,
 'HRL': 0.24110671936758893,
 'HSV': 0.24435461388346807,
 'HTS': 0.36036036036036034,
 'HVN': 0.2178477690288714,
 'HYA': 0.46875,
 'HYS': 0.25817361894024804,
 'IAD': 0.2724089361868618,
 'IAG': 0.2841614906832298,
 'IAH': 0.3138955568639884,
 'ICT': 0.25414722654224986,
 'IDA': 0.21092757306226176,
 'ILM': 0.2400559664201479,
 'IMT': 0.21218487394957983,
 'IND': 0.25473969721291967,
 'INL': 0.19402985074626866,
 'ISN': 0.2299794661190965,
 'ISP': 0.2247412518482011,
 'ITH': 0.2618421052631579,
 'ITO': 0.1759581881533101,
 'JAC': 0.3254385964912281,
 'JAN': 0.28089698195919743,
 'JAX': 0.24247631989129131,
 'JFK': 0.2704947866486822,
 'JLN': 0.3002028397565923,
 'JMS': 0.2679355783308931,
 'JNU': 0.23164861612515042,
 'KOA': 0.18186475409836064,
 'KTN': 0.20972300734878463,
 'LAN': 0.27482195224130707,
 'LAR': 0.25968109339407747,
 'LAS': 0.286686800673334,
 'LAW': 0.25411522633744854,
 'LAX': 0.26714334144913243,
 'LBB': 0.24736431081608748,
 'LBE': 0.18345323741007194,
 'LBF': 0.19910514541387025,
 'LBL': 0.23937360178970918,
 'LCH': 0.226890756302521,
 'LCK': 0.4105011933174224,
 'LEX': 0.25952948183442526,
 'LFT': 0.2964718272775145,
 'LGA': 0.3282847436838835,
 'LGB': 0.2110773387369132,
 'LIH': 0.22836744407425036,
 'LIT': 0.2801769741271521,
 'LNK': 0.2566481137909709,
 'LRD': 0.2547931382441978,
 'LSE': 0.25888324873096447,
 'LWB': 0.289760348583878,
 'LWS': 0.08536585365853659,
 'LYH': 0.1409295352323838,
 'MAF': 0.23385490753911806,
 'MBS': 0.19111111111111112,
 'MCI': 0.24876981957353744,
 'MCO': 0.3091492807288362,
 'MDT': 0.2822269807280514,
 'MDW': 0.3266531077930453,
 'MEI': 0.3765867418899859,
 'MEM': 0.27255015533673843,
 'MFE': 0.2602303357020338,
 'MFR': 0.2672530446549391,
 'MGM': 0.25463306152705706,
 'MHK': 0.27044025157232704,
 'MHT': 0.23260504201680673,
 'MIA': 0.30763758551795123,
 'MKE': 0.25585009546645354,
 'MKG': 0.25440313111545987,
 'MLB': 0.19750519750519752,
 'MLI': 0.29463525404484814,
 'MLU': 0.2610091743119266,
 'MMH': 0.4678362573099415,
 'MOB': 0.2689243027888446,
 'MOT': 0.2232612507305669,
 'MQT': 0.28434197886647455,
 'MRY': 0.24462449361171704,
 'MSN': 0.27119313135300505,
 'MSO': 0.2838884585592564,
 'MSP': 0.2402252032383485,
 'MSY': 0.29363570204474493,
 'MTJ': 0.3087693441414886,
 'MVY': 0.3475177304964539,
 'MYR': 0.25591274397244546,
 'OAJ': 0.2504725897920605,
 'OAK': 0.28325167380653105,
 'OGD': 0.5584415584415584,
 'OGG': 0.25344701583434837,
 'OGS': 0.27540106951871657,
 'OKC': 0.2698196665532494,
 'OMA': 0.2626682085786375,
 'OME': 0.1596153846153846,
 'ONT': 0.2325189553496209,
 'ORD': 0.3644384036591966,
 'ORF': 0.25603945035460995,
 'ORH': 0.32727272727272727,
 'OTH': 0.39338235294117646,
 'OTZ': 0.16955684007707128,
 'OWB': 0.3333333333333333,
 'PAE': 0.29282700421940927,
 'PAH': 0.2802617230098146,
 'PBG': 0.29253731343283584,
 'PBI': 0.2755469688266931,
 'PDX': 0.2436087958476018,
 'PGD': 0.24606060606060606,
 'PGV': 0.18518518518518517,
 'PHF': 0.19901315789473684,
 'PHL': 0.2897868234861711,
 'PHX': 0.2801263925585995,
 'PIA': 0.2668639053254438,
 'PIB': 0.2514506769825919,
 'PIE': 0.21571596836614504,
 'PIH': 0.15821256038647344,
 'PIR': 0.22718052738336714,
 'PIT': 0.2435925164918352,
 'PLN': 0.2335483870967742,
 'PNS': 0.24060150375939848,
 'PPG': 0.5274725274725275,
 'PRC': 0.39365671641791045,
 'PSC': 0.24097995545657017,
 'PSE': 0.3032258064516129,
 'PSG': 0.2336448598130841,
 'PSM': 0.3281733746130031,
 'PSP': 0.2617165757542024,
 'PUB': 0.30194319880418535,
 'PVD': 0.2451811295282382,
 'PVU': 0.32667876588021777,
 'PWM': 0.26705796038151136,
 'RAP': 0.28966083150984684,
 'RDD': 0.29124236252545826,
 'RDM': 0.2909891598915989,
 'RDU': 0.2788990437505289,
 'RFD': 0.34982935153583616,
 'RHI': 0.2037037037037037,
 'RIC': 0.2629379090359127,
 'RKS': 0.23738317757009345,
 'RNO': 0.2299653932279297,
 'ROA': 0.2751322751322751,
 'ROC': 0.2666977611940298,
 'ROW': 0.17315175097276264,
 'RST': 0.2964782964782965,
 'RSW': 0.2467552775605942,
 'SAF': 0.24336618650492797,
 'SAN': 0.26054984419139704,
 'SAT': 0.23046498487718947,
 'SAV': 0.26638997771116746,
 'SBA': 0.24798387096774194,
 'SBN': 0.26658814291323124,
 'SBP': 0.2997125685915861,
 'SCC': 0.1408839779005525,
 'SCE': 0.2661596958174905,
 'SCK': 0.3835978835978836,
 'SDF': 0.263396099905012,
 'SEA': 0.2900465679778897,
 'SFB': 0.29087359687652514,
 'SFO': 0.30966811199406824,
 'SGF': 0.3207726409119696,
 'SGU': 0.26365054602184085,
 'SHD': 0.24517374517374518,
 'SHV': 0.3130434782608696,
 'SIT': 0.17377731529656607,
 'SJC': 0.24223050582982966,
 'SJT': 0.20901932712956334,
 'SJU': 0.29873165879134544,
 'SLC': 0.22501429088066824,
 'SLN': 0.2955223880597015,
 'SMF': 0.23371979914293978,
 'SMX': 0.30935251798561153,
 'SNA': 0.237487078595485,
 'SPI': 0.2789598108747045,
 'SPN': 0.16279069767441862,
 'SPS': 0.23019271948608136,
 'SRQ': 0.2771392081736909,
 'STC': 0.3883495145631068,
 'STL': 0.30373186593296647,
 'STS': 0.2441025641025641,
 'STT': 0.252158273381295,
 'STX': 0.16913946587537093,
 'SUN': 0.24822695035460993,
 'SUX': 0.3793103448275862,
 'SWF': 0.349768875192604,
 'SWO': 0.21293375394321767,
 'SYR': 0.24494360171139634,
 'TLH': 0.2292009884678748,
 'TOL': 0.24935064935064935,
 'TPA': 0.2703459202534988,
 'TRI': 0.22780797101449277,
 'TTN': 0.35766092475067995,
 'TUL': 0.24534781566967495,
 'TUS': 0.22480457844779453,
 'TVC': 0.31767337807606266,
 'TWF': 0.22808870116156282,
 'TXK': 0.2229654403567447,
 'TYR': 0.2393617021276596,
 'TYS': 0.27082868821999256,
 'UIN': 0.2909090909090909,
 'USA': 0.39902439024390246,
 'VEL': 0.27954545454545454,
 'VLD': 0.17564102564102563,
 'VPS': 0.26243177683444513,
 'WRG': 0.22794117647058823,
 'WYS': 0.1625615763546798,
 'XNA': 0.2870766835344492,
 'XWA': 0.3618421052631579,
 'YAK': 0.20348837209302326,
 'YUM': 0.20897615708274894}

In [22]:
des_airport_means=data.groupby('DESTINATION_AIRPORT')['OUTCOME'].mean()
des_airport_means

DESTINATION_AIRPORT
ABE    0.258436
ABI    0.319111
ABQ    0.301621
ABR    0.152700
ABY    0.249322
         ...
WYS    0.179104
XNA    0.299826
XWA    0.189189
YAK    0.231911
YUM    0.258503
Name: OUTCOME, Length: 360, dtype: float64

In [23]:
des_di=dict(des_airport_means)
des_di

{'ABE': 0.2584362139917695,
 'ABI': 0.3191105769230769,
 'ABQ': 0.301620940489146,
 'ABR': 0.1527001862197393,
 'ABY': 0.24932249322493225,
 'ACK': 0.2325301204819277,
 'ACT': 0.282089552238806,
 'ACV': 0.2926470588235294,
 'ACY': 0.24242424242424243,
 'ADK': 0.0975609756097561,
 'ADQ': 0.2328159645232816,
 'AEX': 0.26663961038961037,
 'AGS': 0.2384252841696701,
 'AKN': 0.12903225806451613,
 'ALB': 0.29608096468561584,
 'ALO': 0.390715667311412,
 'AMA': 0.31669813865659563,
 'ANC': 0.24783983140147522,
 'APN': 0.18561484918793503,
 'ART': 0.32298136645962733,
 'ASE': 0.3683862433862434,
 'ATL': 0.22349287939626553,
 'ATW': 0.2578397212543554,
 'ATY': 0.26649076517150394,
 'AUS': 0.2875318066157761,
 'AVL': 0.30953066513101063,
 'AVP': 0.2736641221374046,
 'AZA': 0.4004550625711035,
 'AZO': 0.28914919852034526,
 'BDL': 0.2839611466477138,
 'BET': 0.1536,
 'BFF': 0.25274725274725274,
 'BFL': 0.2909494725152693,
 'BFM': 0.35772357723577236,
 'BGM': 0.24964739069111425,
 'BGR': 0.32972367438386857,
 'BHM': 0.3119736103312746,
 'BIL': 0.24463937621832357,
 'BIS': 0.2595419847328244,
 'BJI': 0.1717902350813743,
 'BKG': 0.3271604938271605,
 'BLI': 0.22116091109478325,
 'BLV': 0.2890818858560794,
 'BMI': 0.30365093499554763,
 'BNA': 0.2759641490301266,
 'BOI': 0.25111789339200796,
 'BOS': 0.31797176333600174,
 'BPT': 0.26944444444444443,
 'BQK': 0.2537878787878788,
 'BQN': 0.3864406779661017,
 'BRD': 0.16216216216216217,
 'BRO': 0.2808358817533129,
 'BRW': 0.14555765595463138,
 'BTM': 0.11706349206349206,
 'BTR': 0.27375886524822696,
 'BTV': 0.299659960328705,
 'BUF': 0.2847594321383196,
 'BUR': 0.264917918874316,
 'BWI': 0.24327361584800136,
 'BZN': 0.2730627306273063,
 'CAE': 0.29832628287658636,
 'CAK': 0.34777921517895644,
 'CDC': 0.22434782608695653,
 'CDV': 0.311787072243346,
 'CGI': 0.30927835051546393,
 'CHA': 0.267622641509434,
 'CHO': 0.29094727018198785,
 'CHS': 0.27154989384288747,
 'CID': 0.30139950945029576,
 'CIU': 0.24421052631578946,
 'CKB': 0.2909967845659164,
 'CLE': 0.27613293051359517,
 'CLL': 0.24860161591050342,
 'CLT': 0.2547136497571537,
 'CMH': 0.2730057869057075,
 'CMI': 0.36222326895902024,
 'CMX': 0.38016528925619836,
 'CNY': 0.27927927927927926,
 'COD': 0.2057877813504823,
 'COS': 0.3384321223709369,
 'COU': 0.3882495457298607,
 'CPR': 0.1797175866495507,
 'CRP': 0.2927115069135224,
 'CRW': 0.3115302707636142,
 'CSG': 0.23843782117163412,
 'CVG': 0.2853372269332285,
 'CWA': 0.23306666666666667,
 'CYS': 0.19293478260869565,
 'DAB': 0.25182186234817816,
 'DAL': 0.28596866096866097,
 'DAY': 0.3051185022903804,
 'DBQ': 0.3814713896457766,
 'DCA': 0.27611159374506394,
 'DEN': 0.3015424581912648,
 'DFW': 0.3018179183159573,
 'DHN': 0.2618816682832202,
 'DLG': 0.16129032258064516,
 'DLH': 0.26547569588699627,
 'DRO': 0.34048948046371835,
 'DRT': 0.28191489361702127,
 'DSM': 0.2930992638136073,
 'DTW': 0.235876084844017,
 'DVL': 0.27674418604651163,
 'EAR': 0.29018789144050106,
 'EAU': 0.3339920948616601,
 'ECP': 0.2677595628415301,
 'EGE': 0.37799043062200954,
 'EKO': 0.13163064833005894,
 'ELM': 0.1951219512195122,
 'ELP': 0.3159360330973029,
 'ERI': 0.2882882882882883,
 'ESC': 0.2376470588235294,
 'EUG': 0.2847871235721703,
 'EVV': 0.2743150684931507,
 'EWN': 0.2838073128264655,
 'EWR': 0.3771337469662967,
 'EYW': 0.21162021728861596,
 'FAI': 0.20794326241134753,
 'FAR': 0.2854237288135593,
 'FAT': 0.2546861377506539,
 'FAY': 0.28691520467836257,
 'FCA': 0.21431787483115713,
 'FLG': 0.18924438393464943,
 'FLL': 0.31989225144993266,
 'FNT': 0.28973765432098764,
 'FSD': 0.3052409291610674,
 'FSM': 0.2820999367488931,
 'FWA': 0.2858521520941903,
 'GCC': 0.3009009009009009,
 'GCK': 0.29980657640232106,
 'GEG': 0.29139748384903097,
 'GFK': 0.20206584893479665,
 'GGG': 0.19236417033773862,
 'GJT': 0.22174629324546952,
 'GNV': 0.2753510140405616,
 'GPT': 0.28046186569431786,
 'GRB': 0.30374592833876224,
 'GRI': 0.23447401774397972,
 'GRK': 0.2929373996789727,
 'GRR': 0.316305358803749,
 'GSO': 0.29237525696131567,
 'GSP': 0.2894470667565745,
 'GST': 0.14285714285714285,
 'GTF': 0.17541229385307347,
 'GTR': 0.2465437788018433,
 'GUC': 0.391304347826087,
 'GUM': 0.233387358184765,
 'HDN': 0.3404255319148936,
 'HGR': 0.2896551724137931,
 'HHH': 0.31296758104738154,
 'HIB': 0.10675381263616558,
 'HLN': 0.12625250501002003,
 'HNL': 0.24681842624126188,
 'HOB': 0.3421985815602837,
 'HOU': 0.2743330601839206,
 'HPN': 0.3223465016658734,
 'HRL': 0.2763480392156863,
 'HSV': 0.27355149454596966,
 'HTS': 0.289048473967684,
 'HVN': 0.23915900131406045,
 'HYA': 0.29508196721311475,
 'HYS': 0.2918552036199095,
 'IAD': 0.2601094826063924,
 'IAG': 0.1829652996845426,
 'IAH': 0.3043445409897998,
 'ICT': 0.3115616578981137,
 'IDA': 0.20025268477574226,
 'ILM': 0.28838049367850693,
 'IMT': 0.15690376569037656,
 'IND': 0.284531987089299,
 'INL': 0.1704312114989733,
 'ISN': 0.14712153518123666,
 'ISP': 0.30047064651969285,
 'ITH': 0.2393980848153215,
 'ITO': 0.17722357095563893,
 'JAC': 0.3148479427549195,
 'JAN': 0.30434782608695654,
 'JAX': 0.2876712328767123,
 'JFK': 0.2811789446715843,
 'JLN': 0.29931972789115646,
 'JMS': 0.2323943661971831,
 'JNU': 0.20257330939557153,
 'KOA': 0.20409391932570742,
 'KTN': 0.21465076660988075,
 'LAN': 0.3078547297297297,
 'LAR': 0.29836829836829837,
 'LAS': 0.29065781104144467,
 'LAW': 0.2670744138634047,
 'LAX': 0.29132265699443644,
 'LBB': 0.29964884900507216,
 'LBE': 0.27476415094339623,
 'LBF': 0.2816593886462882,
 'LBL': 0.2595078299776286,
 'LCH': 0.2801418439716312,
 'LCK': 0.30609756097560975,
 'LEX': 0.296711509715994,
 'LFT': 0.27118200836820083,
 'LGA': 0.34651625103033634,
 'LGB': 0.25389262316004424,
 'LIH': 0.20353813962335934,
 'LIT': 0.29972545678311086,
 'LNK': 0.2821279139270771,
 'LRD': 0.26865671641791045,
 'LSE': 0.268944099378882,
 'LWB': 0.3514644351464435,
 'LWS': 0.0993103448275862,
 'LYH': 0.26403641881638845,
 'MAF': 0.30399094254174924,
 'MBS': 0.24813233724653147,
 'MCI': 0.27926738101171195,
 'MCO': 0.29520977865873804,
 'MDT': 0.2741655830082358,
 'MDW': 0.26632906331728606,
 'MEI': 0.36737588652482267,
 'MEM': 0.30035688044505093,
 'MFE': 0.32035053554040893,
 'MFR': 0.2739450770261219,
 'MGM': 0.2673374056773266,
 'MHK': 0.3229166666666667,
 'MHT': 0.2878686327077748,
 'MIA': 0.26213224143160446,
 'MKE': 0.2877335571359159,
 'MKG': 0.4308617234468938,
 'MLB': 0.23950870010235414,
 'MLI': 0.26788218793828894,
 'MLU': 0.26442085832948775,
 'MMH': 0.35435435435435436,
 'MOB': 0.29181228157763356,
 'MOT': 0.2231833910034602,
 'MQT': 0.27121951219512197,
 'MRY': 0.2635413367120684,
 'MSN': 0.30131259115216336,
 'MSO': 0.2593297791317593,
 'MSP': 0.2368766293835674,
 'MSY': 0.29094439375862635,
 'MTJ': 0.3173431734317343,
 'MVY': 0.22113022113022113,
 'MYR': 0.26944949954504094,
 'OAJ': 0.2882797731568998,
 'OAK': 0.27369312495188236,
 'OGD': 0.30864197530864196,
 'OGG': 0.21951338914182209,
 'OGS': 0.2962962962962963,
 'OKC': 0.3223525450361973,
 'OMA': 0.2845587851589,
 'OME': 0.14512922465208747,
 'ONT': 0.285431654676259,
 'ORD': 0.31639218752545245,
 'ORF': 0.2992793791574279,
 'ORH': 0.31584948688711517,
 'OTH': 0.3359375,
 'OTZ': 0.17142857142857143,
 'OWB': 0.24096385542168675,
 'PAE': 0.28789161727349705,
 'PAH': 0.30802139037433157,
 'PBG': 0.30666666666666664,
 'PBI': 0.3065425394362555,
 'PDX': 0.26281291101576143,
 'PGD': 0.33528265107212474,
 'PGV': 0.0967741935483871,
 'PHF': 0.24039517014270034,
 'PHL': 0.2664258349535785,
 'PHX': 0.27981098860372466,
 'PIA': 0.29454651501895596,
 'PIB': 0.32755298651252407,
 'PIE': 0.2668936170212766,
 'PIH': 0.13374233128834356,
 'PIR': 0.24364406779661016,
 'PIT': 0.2723515747393442,
 'PLN': 0.22531645569620254,
 'PNS': 0.3063255913518142,
 'PPG': 0.47126436781609193,
 'PRC': 0.2636363636363636,
 'PSC': 0.24508459076360312,
 'PSE': 0.4098883572567783,
 'PSG': 0.3146067415730337,
 'PSM': 0.25,
 'PSP': 0.2978723404255319,
 'PUB': 0.27370030581039756,
 'PVD': 0.2915126367408525,
 'PVU': 0.2765567765567766,
 'PWM': 0.30011047011169756,
 'RAP': 0.29638888888888887,
 'RDD': 0.29183673469387755,
 'RDM': 0.2718281036834925,
 'RDU': 0.2828327724511609,
 'RFD': 0.26916524701873934,
 'RHI': 0.19365609348914858,
 'RIC': 0.28491774318206914,
 'RKS': 0.26860254083484575,
 'RNO': 0.26324346294540035,
 'ROA': 0.25497630331753557,
 'ROC': 0.2916744972749483,
 'ROW': 0.22692307692307692,
 'RST': 0.30007980845969673,
 'RSW': 0.27299703264094954,
 'SAF': 0.29460895975702356,
 'SAN': 0.2947424861606237,
 'SAT': 0.2947140236785059,
 'SAV': 0.2963393826586009,
 'SBA': 0.293747687754347,
 'SBN': 0.28759945662720743,
 'SBP': 0.2828042328042328,
 'SCC': 0.18270571827057183,
 'SCE': 0.3014426727410782,
 'SCK': 0.23834886817576564,
 'SDF': 0.2786903502422184,
 'SEA': 0.30384118207637073,
 'SFB': 0.3500360490266763,
 'SFO': 0.34365879222768686,
 'SGF': 0.31145981930575367,
 'SGU': 0.2664609053497942,
 'SHD': 0.31467181467181465,
 'SHV': 0.2893118031526336,
 'SIT': 0.23511604439959638,
 'SJC': 0.2545592048401037,
 'SJT': 0.2707263389581805,
 'SJU': 0.33791426870410796,
 'SLC': 0.24030466075047166,
 'SLN': 0.3062130177514793,
 'SMF': 0.2734276398822045,
 'SMX': 0.2894736842105263,
 'SNA': 0.26806750496360027,
 'SPI': 0.34872979214780603,
 'SPN': 0.18681318681318682,
 'SPS': 0.2295973884657236,
 'SRQ': 0.2688916876574307,
 'STC': 0.3904761904761905,
 'STL': 0.2882723180496355,
 'STS': 0.2983367983367983,
 'STT': 0.2737884683409975,
 'STX': 0.26138032305433184,
 'SUN': 0.18552497451580022,
 'SUX': 0.37142857142857144,
 'SWF': 0.30023273855702093,
 'SWO': 0.2837423312883436,
 'SYR': 0.2914592484138604,
 'TLH': 0.25261396905060646,
 'TOL': 0.3006666666666667,
 'TPA': 0.2777445881360697,
 'TRI': 0.24943515589697243,
 'TTN': 0.3093821510297483,
 'TUL': 0.3001344830314057,
 'TUS': 0.2994235095613048,
 'TVC': 0.29856115107913667,
 'TWF': 0.14341590612777053,
 'TXK': 0.23458149779735682,
 'TYR': 0.2440318302387268,
 'TYS': 0.3117762069484133,
 'UIN': 0.34101382488479265,
 'USA': 0.3073263558515699,
 'VEL': 0.25339366515837103,
 'VLD': 0.1880674448767834,
 'VPS': 0.3077269993986771,
 'WRG': 0.312015503875969,
 'WYS': 0.1791044776119403,
 'XNA': 0.2998261877172654,
 'XWA': 0.1891891891891892,
 'YAK': 0.23191094619666047,
 'YUM': 0.2585034013605442}

In [0]:
############ DO RUN THIS ############



df['ORIGIN_AIRPORT']=df['ORIGIN_AIRPORT'].map(df.groupby('ORIGIN_AIRPORT')['OUTCOME'].mean())
df['DESTINATION_AIRPORT']=df['DESTINATION_AIRPORT'].map(df.groupby('DESTINATION_AIRPORT')['OUTCOME'].mean())
df

In [24]:
data['ORIGIN_AIRPORT']=data['ORIGIN_AIRPORT'].map(ori_di)
data['DESTINATION_AIRPORT']=data['DESTINATION_AIRPORT'].map(des_di)
data

         YEAR  MONTH  DAY  ...  WHEELS_OFF_HOUR  WHEELS_OFF_MINUTE  OUTCOME
985289   2019      2   17  ...               17                  1        0
5243685  2019      9    4  ...               11                 56        1
1604102  2019      3    3  ...               20                  3        1
3196153  2019      6   17  ...               17                 27        1
1910817  2019      4   10  ...                8                 48        1
...       ...    ...  ...  ...              ...                ...      ...
4985584  2019      9    3  ...                6                 50        0
4390712  2019      7   24  ...               12                 19        0
3684895  2019      7   19  ...               18                 50        0
560968   2019      1   22  ...                5                 55        0
1429176  2019      3    1  ...               15                 19        1

[5449996 rows x 59 columns]

In [25]:
dep_del_means=data.groupby('DEPARTURE_DELAY')['OUTCOME'].mean()
dep_del_means

DEPARTURE_DELAY
-82.0      0.0
-66.0      0.0
-62.0      0.0
-55.0      0.0
-52.0      0.0
          ...
 2036.0    1.0
 2079.0    1.0
 2209.0    1.0
 2315.0    1.0
 2710.0    1.0
Name: OUTCOME, Length: 1527, dtype: float64

In [26]:
dep_del_di=dict(dep_del_means)
dep_del_di

{-82.0: 0.0,
 -66.0: 0.0,
 -62.0: 0.0,
 -55.0: 0.0,
 -52.0: 0.0,
 -50.0: 0.0,
 -49.0: 0.0,
 -48.0: 0.0,
 -47.0: 0.0,
 -46.0: 0.0,
 -45.0: 0.0,
 -44.0: 0.0,
 -42.0: 0.2,
 -41.0: 0.0,
 -40.0: 0.0,
 -39.0: 0.0,
 -38.0: 0.0,
 -37.0: 0.0,
 -36.0: 0.0,
 -35.0: 0.0,
 -34.0: 0.07692307692307693,
 -33.0: 0.0,
 -32.0: 0.04081632653061224,
 -31.0: 0.058823529411764705,
 -30.0: 0.012987012987012988,
 -29.0: 0.015625,
 -28.0: 0.014285714285714285,
 -27.0: 0.009569377990430622,
 -26.0: 0.007352941176470588,
 -25.0: 0.02669902912621359,
 -24.0: 0.016544117647058824,
 -23.0: 0.016581632653061226,
 -22.0: 0.02966507177033493,
 -21.0: 0.024163568773234202,
 -20.0: 0.024793388429752067,
 -19.0: 0.03533123028391167,
 -18.0: 0.032936078006500544,
 -17.0: 0.036060606060606064,
 -16.0: 0.041574337870634165,
 -15.0: 0.04168753129694542,
 -14.0: 0.04588485754405037,
 -13.0: 0.04785796989579313,
 -12.0: 0.05224304372515616,
 -11.0: 0.055674669224475976,
 -10.0: 0.06016437146057135,
 -9.0: 0.06513501814670529,
 -8.0: 0.0679805084135481,
 -7.0: 0.07098256511355688,
 -6.0: 0.07699985407850576,
 -5.0: 0.07949881790056335,
 -4.0: 0.09136035533153017,
 -3.0: 0.10142320694651147,
 -2.0: 0.11564653240244907,
 -1.0: 0.132316435055611,
 0.0: 0.1570915272572731,
 1.0: 0.17274630723177334,
 2.0: 0.19371099375900144,
 3.0: 0.21629697871636785,
 4.0: 0.2422589888159719,
 5.0: 0.26549840104398204,
 6.0: 0.2971553890729802,
 7.0: 0.3267013498312711,
 8.0: 0.35863988337530056,
 9.0: 0.39796987691865127,
 10.0: 0.43520824760130816,
 11.0: 0.47361916531989734,
 12.0: 0.5113148753575807,
 13.0: 0.5477041442719559,
 14.0: 0.5886809913531335,
 15.0: 0.6267759562841531,
 16.0: 0.6635029064993925,
 17.0: 0.698816263510036,
 18.0: 0.7376060251535537,
 19.0: 0.766603046001636,
 20.0: 0.7954980842911877,
 21.0: 0.8214255045083727,
 22.0: 0.8455451884376144,
 23.0: 0.8646207679213165,
 24.0: 0.8784704821088504,
 25.0: 0.8977151831399767,
 26.0: 0.9176868556701031,
 27.0: 0.9252076018503037,
 28.0: 0.9380997512143111,
 29.0: 0.9463001340972815,
 30.0: 0.9542060726729716,
 31.0: 0.9616101131071191,
 32.0: 0.9671737938596491,
 33.0: 0.9740732648751002,
 34.0: 0.974106491611962,
 35.0: 0.9788129226145755,
 36.0: 0.9811459955734076,
 37.0: 0.9833292473645502,
 38.0: 0.9893515712925288,
 39.0: 0.9883488392313712,
 40.0: 0.9909017205657148,
 41.0: 0.9931852128454071,
 42.0: 0.9929139972820812,
 43.0: 0.9949233622962023,
 44.0: 0.9960470302047436,
 45.0: 0.9966502669318539,
 46.0: 0.9966544355709044,
 47.0: 0.99687255668491,
 48.0: 0.9965333949618673,
 49.0: 0.9971523493118177,
 50.0: 0.9981916817359855,
 51.0: 0.9980945121951219,
 52.0: 0.9983059682043263,
 53.0: 0.9989678751128886,
 54.0: 0.9991898460707535,
 55.0: 0.9990363436123348,
 56.0: 0.9984209015216767,
 57.0: 0.9994212962962963,
 58.0: 0.9997033521210323,
 59.0: 0.999410551134689,
 60.0: 0.9993838570548367,
 61.0: 0.9995238095238095,
 62.0: 0.9998378203048979,
 63.0: 1.0,
 64.0: 0.9998275862068966,
 65.0: 1.0,
 66.0: 1.0,
 67.0: 0.9998122770790313,
 68.0: 1.0,
 69.0: 1.0,
 70.0: 1.0,
 71.0: 1.0,
 72.0: 1.0,
 73.0: 1.0,
 74.0: 1.0,
 75.0: 1.0,
 76.0: 1.0,
 77.0: 1.0,
 78.0: 1.0,
 79.0: 1.0,
 80.0: 1.0,
 81.0: 1.0,
 82.0: 1.0,
 83.0: 1.0,
 84.0: 1.0,
 85.0: 1.0,
 86.0: 1.0,
 87.0: 0.9997190221972464,
 88.0: 1.0,
 89.0: 1.0,
 90.0: 1.0,
 91.0: 1.0,
 92.0: 1.0,
 93.0: 1.0,
 94.0: 1.0,
 95.0: 1.0,
 96.0: 1.0,
 97.0: 1.0,
 98.0: 1.0,
 99.0: 1.0,
 100.0: 1.0,
 101.0: 1.0,
 102.0: 1.0,
 103.0: 1.0,
 104.0: 1.0,
 105.0: 1.0,
 106.0: 1.0,
 107.0: 1.0,
 108.0: 1.0,
 109.0: 1.0,
 110.0: 1.0,
 111.0: 1.0,
 112.0: 1.0,
 113.0: 1.0,
 114.0: 1.0,
 115.0: 1.0,
 116.0: 1.0,
 117.0: 1.0,
 118.0: 1.0,
 119.0: 1.0,
 120.0: 1.0,
 121.0: 1.0,
 122.0: 1.0,
 123.0: 1.0,
 124.0: 1.0,
 125.0: 1.0,
 126.0: 1.0,
 127.0: 1.0,
 128.0: 1.0,
 129.0: 1.0,
 130.0: 1.0,
 131.0: 1.0,
 132.0: 1.0,
 133.0: 1.0,
 134.0: 1.0,
 135.0: 1.0,
 136.0: 1.0,
 137.0: 1.0,
 138.0: 1.0,
 139.0: 1.0,
 140.0: 1.0,
 141.0: 1.0,
 142.0: 1.0,
 143.0: 1.0,
 144.0: 1.0,
 145.0: 1.0,
 146.0: 1.0,
 147.0: 1.0,
 148.0: 1.0,
 149.0: 1.0,
 150.0: 1.0,
 151.0: 1.0,
 152.0: 1.0,
 153.0: 1.0,
 154.0: 1.0,
 155.0: 1.0,
 156.0: 1.0,
 157.0: 1.0,
 158.0: 1.0,
 159.0: 1.0,
 160.0: 0.9991095280498664,
 161.0: 1.0,
 162.0: 1.0,
 163.0: 0.9990118577075099,
 164.0: 1.0,
 165.0: 1.0,
 166.0: 1.0,
 167.0: 1.0,
 168.0: 1.0,
 169.0: 1.0,
 170.0: 0.9989648033126294,
 171.0: 1.0,
 172.0: 1.0,
 173.0: 1.0,
 174.0: 1.0,
 175.0: 1.0,
 176.0: 1.0,
 177.0: 1.0,
 178.0: 1.0,
 179.0: 1.0,
 180.0: 1.0,
 181.0: 1.0,
 182.0: 1.0,
 183.0: 1.0,
 184.0: 1.0,
 185.0: 1.0,
 186.0: 1.0,
 187.0: 1.0,
 188.0: 1.0,
 189.0: 1.0,
 190.0: 1.0,
 191.0: 1.0,
 192.0: 1.0,
 193.0: 1.0,
 194.0: 1.0,
 195.0: 1.0,
 196.0: 1.0,
 197.0: 1.0,
 198.0: 1.0,
 199.0: 1.0,
 200.0: 1.0,
 201.0: 1.0,
 202.0: 1.0,
 203.0: 1.0,
 204.0: 1.0,
 205.0: 1.0,
 206.0: 1.0,
 207.0: 1.0,
 208.0: 1.0,
 209.0: 1.0,
 210.0: 1.0,
 211.0: 1.0,
 212.0: 1.0,
 213.0: 1.0,
 214.0: 1.0,
 215.0: 0.9978213507625272,
 216.0: 1.0,
 217.0: 1.0,
 218.0: 1.0,
 219.0: 1.0,
 220.0: 1.0,
 221.0: 1.0,
 222.0: 1.0,
 223.0: 1.0,
 224.0: 1.0,
 225.0: 1.0,
 226.0: 1.0,
 227.0: 1.0,
 228.0: 1.0,
 229.0: 1.0,
 230.0: 1.0,
 231.0: 1.0,
 232.0: 1.0,
 233.0: 1.0,
 234.0: 1.0,
 235.0: 1.0,
 236.0: 1.0,
 237.0: 1.0,
 238.0: 1.0,
 239.0: 1.0,
 240.0: 1.0,
 241.0: 1.0,
 242.0: 1.0,
 243.0: 1.0,
 244.0: 1.0,
 245.0: 1.0,
 246.0: 1.0,
 247.0: 1.0,
 248.0: 1.0,
 249.0: 1.0,
 250.0: 1.0,
 251.0: 1.0,
 252.0: 1.0,
 253.0: 1.0,
 254.0: 1.0,
 255.0: 1.0,
 256.0: 1.0,
 257.0: 1.0,
 258.0: 1.0,
 259.0: 1.0,
 260.0: 1.0,
 261.0: 1.0,
 262.0: 1.0,
 263.0: 1.0,
 264.0: 1.0,
 265.0: 1.0,
 266.0: 1.0,
 267.0: 1.0,
 268.0: 1.0,
 269.0: 1.0,
 270.0: 1.0,
 271.0: 1.0,
 272.0: 1.0,
 273.0: 1.0,
 274.0: 1.0,
 275.0: 1.0,
 276.0: 1.0,
 277.0: 1.0,
 278.0: 1.0,
 279.0: 1.0,
 280.0: 1.0,
 281.0: 1.0,
 282.0: 1.0,
 283.0: 1.0,
 284.0: 1.0,
 285.0: 1.0,
 286.0: 1.0,
 287.0: 1.0,
 288.0: 1.0,
 289.0: 1.0,
 290.0: 1.0,
 291.0: 1.0,
 292.0: 1.0,
 293.0: 1.0,
 294.0: 1.0,
 295.0: 1.0,
 296.0: 1.0,
 297.0: 1.0,
 298.0: 1.0,
 299.0: 1.0,
 300.0: 1.0,
 301.0: 1.0,
 302.0: 1.0,
 303.0: 1.0,
 304.0: 1.0,
 305.0: 1.0,
 306.0: 1.0,
 307.0: 1.0,
 308.0: 1.0,
 309.0: 1.0,
 310.0: 1.0,
 311.0: 1.0,
 312.0: 1.0,
 313.0: 1.0,
 314.0: 1.0,
 315.0: 1.0,
 316.0: 1.0,
 317.0: 1.0,
 318.0: 1.0,
 319.0: 1.0,
 320.0: 1.0,
 321.0: 1.0,
 322.0: 1.0,
 323.0: 1.0,
 324.0: 1.0,
 325.0: 1.0,
 326.0: 1.0,
 327.0: 1.0,
 328.0: 1.0,
 329.0: 1.0,
 330.0: 1.0,
 331.0: 1.0,
 332.0: 1.0,
 333.0: 1.0,
 334.0: 1.0,
 335.0: 1.0,
 336.0: 1.0,
 337.0: 1.0,
 338.0: 1.0,
 339.0: 1.0,
 340.0: 1.0,
 341.0: 1.0,
 342.0: 1.0,
 343.0: 1.0,
 344.0: 1.0,
 345.0: 1.0,
 346.0: 1.0,
 347.0: 1.0,
 348.0: 1.0,
 349.0: 1.0,
 350.0: 1.0,
 351.0: 1.0,
 352.0: 1.0,
 353.0: 1.0,
 354.0: 1.0,
 355.0: 1.0,
 356.0: 1.0,
 357.0: 1.0,
 358.0: 1.0,
 359.0: 1.0,
 360.0: 1.0,
 361.0: 1.0,
 362.0: 1.0,
 363.0: 1.0,
 364.0: 1.0,
 365.0: 1.0,
 366.0: 1.0,
 367.0: 1.0,
 368.0: 1.0,
 369.0: 1.0,
 370.0: 1.0,
 371.0: 1.0,
 372.0: 1.0,
 373.0: 1.0,
 374.0: 1.0,
 375.0: 1.0,
 376.0: 1.0,
 377.0: 1.0,
 378.0: 1.0,
 379.0: 1.0,
 380.0: 1.0,
 381.0: 1.0,
 382.0: 1.0,
 383.0: 1.0,
 384.0: 1.0,
 385.0: 1.0,
 386.0: 1.0,
 387.0: 1.0,
 388.0: 1.0,
 389.0: 1.0,
 390.0: 1.0,
 391.0: 1.0,
 392.0: 1.0,
 393.0: 1.0,
 394.0: 1.0,
 395.0: 1.0,
 396.0: 1.0,
 397.0: 1.0,
 398.0: 1.0,
 399.0: 1.0,
 400.0: 1.0,
 401.0: 1.0,
 402.0: 1.0,
 403.0: 1.0,
 404.0: 1.0,
 405.0: 1.0,
 406.0: 1.0,
 407.0: 1.0,
 408.0: 1.0,
 409.0: 1.0,
 410.0: 1.0,
 411.0: 1.0,
 412.0: 1.0,
 413.0: 1.0,
 414.0: 1.0,
 415.0: 1.0,
 416.0: 1.0,
 417.0: 1.0,
 418.0: 1.0,
 419.0: 1.0,
 420.0: 1.0,
 421.0: 1.0,
 422.0: 1.0,
 423.0: 1.0,
 424.0: 1.0,
 425.0: 1.0,
 426.0: 1.0,
 427.0: 1.0,
 428.0: 1.0,
 429.0: 1.0,
 430.0: 1.0,
 431.0: 1.0,
 432.0: 1.0,
 433.0: 1.0,
 434.0: 1.0,
 435.0: 1.0,
 436.0: 1.0,
 437.0: 1.0,
 438.0: 1.0,
 439.0: 1.0,
 440.0: 1.0,
 441.0: 1.0,
 442.0: 1.0,
 443.0: 1.0,
 444.0: 1.0,
 445.0: 1.0,
 446.0: 1.0,
 447.0: 1.0,
 448.0: 1.0,
 449.0: 1.0,
 450.0: 1.0,
 451.0: 1.0,
 452.0: 1.0,
 453.0: 1.0,
 454.0: 1.0,
 455.0: 1.0,
 456.0: 1.0,
 457.0: 1.0,
 458.0: 1.0,
 459.0: 1.0,
 460.0: 1.0,
 461.0: 1.0,
 462.0: 1.0,
 463.0: 1.0,
 464.0: 1.0,
 465.0: 1.0,
 466.0: 1.0,
 467.0: 1.0,
 468.0: 1.0,
 469.0: 1.0,
 470.0: 1.0,
 471.0: 1.0,
 472.0: 1.0,
 473.0: 1.0,
 474.0: 1.0,
 475.0: 1.0,
 476.0: 1.0,
 477.0: 1.0,
 478.0: 1.0,
 479.0: 1.0,
 480.0: 1.0,
 481.0: 1.0,
 482.0: 1.0,
 483.0: 1.0,
 484.0: 1.0,
 485.0: 1.0,
 486.0: 1.0,
 487.0: 1.0,
 488.0: 1.0,
 489.0: 1.0,
 490.0: 1.0,
 491.0: 1.0,
 492.0: 1.0,
 493.0: 1.0,
 494.0: 1.0,
 495.0: 1.0,
 496.0: 1.0,
 497.0: 1.0,
 498.0: 1.0,
 499.0: 1.0,
 500.0: 1.0,
 501.0: 1.0,
 502.0: 1.0,
 503.0: 1.0,
 504.0: 1.0,
 505.0: 1.0,
 506.0: 1.0,
 507.0: 1.0,
 508.0: 1.0,
 509.0: 1.0,
 510.0: 1.0,
 511.0: 1.0,
 512.0: 1.0,
 513.0: 1.0,
 514.0: 1.0,
 515.0: 1.0,
 516.0: 1.0,
 517.0: 1.0,
 518.0: 1.0,
 519.0: 1.0,
 520.0: 1.0,
 521.0: 1.0,
 522.0: 1.0,
 523.0: 1.0,
 524.0: 1.0,
 525.0: 1.0,
 526.0: 1.0,
 527.0: 1.0,
 528.0: 1.0,
 529.0: 1.0,
 530.0: 1.0,
 531.0: 1.0,
 532.0: 1.0,
 533.0: 1.0,
 534.0: 1.0,
 535.0: 1.0,
 536.0: 1.0,
 537.0: 1.0,
 538.0: 1.0,
 539.0: 1.0,
 540.0: 1.0,
 541.0: 1.0,
 542.0: 1.0,
 543.0: 1.0,
 544.0: 1.0,
 545.0: 1.0,
 546.0: 1.0,
 547.0: 1.0,
 548.0: 1.0,
 549.0: 1.0,
 550.0: 1.0,
 551.0: 1.0,
 552.0: 1.0,
 553.0: 1.0,
 554.0: 1.0,
 555.0: 1.0,
 556.0: 1.0,
 557.0: 1.0,
 558.0: 1.0,
 559.0: 1.0,
 560.0: 1.0,
 561.0: 1.0,
 562.0: 1.0,
 563.0: 1.0,
 564.0: 1.0,
 565.0: 1.0,
 566.0: 1.0,
 567.0: 1.0,
 568.0: 1.0,
 569.0: 1.0,
 570.0: 1.0,
 571.0: 1.0,
 572.0: 1.0,
 573.0: 1.0,
 574.0: 1.0,
 575.0: 1.0,
 576.0: 1.0,
 577.0: 1.0,
 578.0: 1.0,
 579.0: 1.0,
 580.0: 1.0,
 581.0: 1.0,
 582.0: 1.0,
 583.0: 1.0,
 584.0: 1.0,
 585.0: 1.0,
 586.0: 1.0,
 587.0: 1.0,
 588.0: 1.0,
 589.0: 1.0,
 590.0: 1.0,
 591.0: 1.0,
 592.0: 1.0,
 593.0: 1.0,
 594.0: 1.0,
 595.0: 1.0,
 596.0: 1.0,
 597.0: 1.0,
 598.0: 1.0,
 599.0: 1.0,
 600.0: 1.0,
 601.0: 1.0,
 602.0: 1.0,
 603.0: 1.0,
 604.0: 1.0,
 605.0: 1.0,
 606.0: 1.0,
 607.0: 1.0,
 608.0: 1.0,
 609.0: 1.0,
 610.0: 1.0,
 611.0: 1.0,
 612.0: 1.0,
 613.0: 1.0,
 614.0: 1.0,
 615.0: 1.0,
 616.0: 1.0,
 617.0: 1.0,
 618.0: 1.0,
 619.0: 1.0,
 620.0: 1.0,
 621.0: 1.0,
 622.0: 1.0,
 623.0: 1.0,
 624.0: 1.0,
 625.0: 1.0,
 626.0: 1.0,
 627.0: 1.0,
 628.0: 1.0,
 629.0: 1.0,
 630.0: 1.0,
 631.0: 1.0,
 632.0: 1.0,
 633.0: 1.0,
 634.0: 1.0,
 635.0: 1.0,
 636.0: 1.0,
 637.0: 1.0,
 638.0: 1.0,
 639.0: 1.0,
 640.0: 1.0,
 641.0: 1.0,
 642.0: 1.0,
 643.0: 1.0,
 644.0: 1.0,
 645.0: 1.0,
 646.0: 1.0,
 647.0: 1.0,
 648.0: 1.0,
 649.0: 1.0,
 650.0: 1.0,
 651.0: 1.0,
 652.0: 1.0,
 653.0: 1.0,
 654.0: 1.0,
 655.0: 1.0,
 656.0: 1.0,
 657.0: 1.0,
 658.0: 1.0,
 659.0: 1.0,
 660.0: 1.0,
 661.0: 1.0,
 662.0: 1.0,
 663.0: 1.0,
 664.0: 1.0,
 665.0: 1.0,
 666.0: 1.0,
 667.0: 1.0,
 668.0: 1.0,
 669.0: 1.0,
 670.0: 1.0,
 671.0: 1.0,
 672.0: 1.0,
 673.0: 1.0,
 674.0: 1.0,
 675.0: 1.0,
 676.0: 1.0,
 677.0: 1.0,
 678.0: 1.0,
 679.0: 1.0,
 680.0: 1.0,
 681.0: 1.0,
 682.0: 1.0,
 683.0: 1.0,
 684.0: 1.0,
 685.0: 1.0,
 686.0: 1.0,
 687.0: 1.0,
 688.0: 1.0,
 689.0: 1.0,
 690.0: 1.0,
 691.0: 1.0,
 692.0: 1.0,
 693.0: 1.0,
 694.0: 1.0,
 695.0: 1.0,
 696.0: 1.0,
 697.0: 1.0,
 698.0: 1.0,
 699.0: 1.0,
 700.0: 1.0,
 701.0: 1.0,
 702.0: 1.0,
 703.0: 1.0,
 704.0: 1.0,
 705.0: 1.0,
 706.0: 1.0,
 707.0: 1.0,
 708.0: 1.0,
 709.0: 1.0,
 710.0: 1.0,
 711.0: 1.0,
 712.0: 1.0,
 713.0: 1.0,
 714.0: 1.0,
 715.0: 1.0,
 716.0: 1.0,
 717.0: 1.0,
 718.0: 1.0,
 719.0: 1.0,
 720.0: 1.0,
 721.0: 1.0,
 722.0: 1.0,
 723.0: 1.0,
 724.0: 1.0,
 725.0: 1.0,
 726.0: 1.0,
 727.0: 1.0,
 728.0: 1.0,
 729.0: 1.0,
 730.0: 1.0,
 731.0: 1.0,
 732.0: 1.0,
 733.0: 1.0,
 734.0: 1.0,
 735.0: 1.0,
 736.0: 1.0,
 737.0: 1.0,
 738.0: 1.0,
 739.0: 1.0,
 740.0: 1.0,
 741.0: 1.0,
 742.0: 1.0,
 743.0: 1.0,
 744.0: 1.0,
 745.0: 1.0,
 746.0: 1.0,
 747.0: 1.0,
 748.0: 1.0,
 749.0: 1.0,
 750.0: 1.0,
 751.0: 1.0,
 752.0: 1.0,
 753.0: 1.0,
 754.0: 1.0,
 755.0: 1.0,
 756.0: 1.0,
 757.0: 1.0,
 758.0: 1.0,
 759.0: 1.0,
 760.0: 1.0,
 761.0: 1.0,
 762.0: 1.0,
 763.0: 1.0,
 764.0: 1.0,
 765.0: 1.0,
 766.0: 1.0,
 767.0: 1.0,
 768.0: 1.0,
 769.0: 1.0,
 770.0: 1.0,
 771.0: 1.0,
 772.0: 1.0,
 773.0: 1.0,
 774.0: 1.0,
 775.0: 1.0,
 776.0: 1.0,
 777.0: 1.0,
 778.0: 1.0,
 779.0: 1.0,
 780.0: 1.0,
 781.0: 1.0,
 782.0: 1.0,
 783.0: 1.0,
 784.0: 1.0,
 785.0: 1.0,
 786.0: 1.0,
 787.0: 1.0,
 788.0: 1.0,
 789.0: 1.0,
 790.0: 1.0,
 791.0: 1.0,
 792.0: 1.0,
 793.0: 1.0,
 794.0: 1.0,
 795.0: 1.0,
 796.0: 1.0,
 797.0: 1.0,
 798.0: 1.0,
 799.0: 1.0,
 800.0: 1.0,
 801.0: 1.0,
 802.0: 1.0,
 803.0: 1.0,
 804.0: 1.0,
 805.0: 1.0,
 806.0: 1.0,
 807.0: 1.0,
 808.0: 1.0,
 809.0: 1.0,
 810.0: 1.0,
 811.0: 1.0,
 812.0: 1.0,
 813.0: 1.0,
 814.0: 1.0,
 815.0: 1.0,
 816.0: 1.0,
 817.0: 1.0,
 818.0: 1.0,
 819.0: 1.0,
 820.0: 1.0,
 821.0: 1.0,
 822.0: 1.0,
 823.0: 1.0,
 824.0: 1.0,
 825.0: 1.0,
 826.0: 1.0,
 827.0: 1.0,
 828.0: 1.0,
 829.0: 1.0,
 830.0: 1.0,
 831.0: 1.0,
 832.0: 1.0,
 833.0: 1.0,
 834.0: 1.0,
 835.0: 1.0,
 836.0: 1.0,
 837.0: 1.0,
 838.0: 1.0,
 839.0: 1.0,
 840.0: 1.0,
 841.0: 1.0,
 842.0: 1.0,
 843.0: 1.0,
 844.0: 1.0,
 845.0: 1.0,
 846.0: 1.0,
 847.0: 1.0,
 848.0: 1.0,
 849.0: 1.0,
 850.0: 1.0,
 851.0: 1.0,
 852.0: 1.0,
 853.0: 1.0,
 854.0: 1.0,
 855.0: 1.0,
 856.0: 1.0,
 857.0: 1.0,
 858.0: 1.0,
 859.0: 1.0,
 860.0: 1.0,
 861.0: 1.0,
 862.0: 1.0,
 863.0: 1.0,
 864.0: 1.0,
 865.0: 1.0,
 866.0: 1.0,
 867.0: 1.0,
 868.0: 1.0,
 869.0: 1.0,
 870.0: 1.0,
 871.0: 1.0,
 872.0: 1.0,
 873.0: 1.0,
 874.0: 1.0,
 875.0: 1.0,
 876.0: 1.0,
 877.0: 1.0,
 878.0: 1.0,
 879.0: 1.0,
 880.0: 1.0,
 881.0: 1.0,
 882.0: 1.0,
 883.0: 1.0,
 884.0: 1.0,
 885.0: 1.0,
 886.0: 1.0,
 887.0: 1.0,
 888.0: 1.0,
 889.0: 1.0,
 890.0: 1.0,
 891.0: 1.0,
 892.0: 1.0,
 893.0: 1.0,
 894.0: 1.0,
 895.0: 1.0,
 896.0: 1.0,
 897.0: 1.0,
 898.0: 1.0,
 899.0: 1.0,
 900.0: 1.0,
 901.0: 1.0,
 902.0: 1.0,
 903.0: 1.0,
 904.0: 1.0,
 905.0: 1.0,
 906.0: 1.0,
 907.0: 1.0,
 908.0: 1.0,
 909.0: 1.0,
 910.0: 1.0,
 911.0: 1.0,
 912.0: 1.0,
 913.0: 1.0,
 914.0: 1.0,
 915.0: 1.0,
 916.0: 1.0,
 917.0: 1.0,
 918.0: 1.0,
 919.0: 1.0,
 920.0: 1.0,
 921.0: 1.0,
 922.0: 1.0,
 923.0: 1.0,
 924.0: 1.0,
 925.0: 1.0,
 926.0: 1.0,
 927.0: 1.0,
 928.0: 1.0,
 929.0: 1.0,
 930.0: 1.0,
 931.0: 1.0,
 932.0: 1.0,
 933.0: 1.0,
 934.0: 1.0,
 935.0: 1.0,
 936.0: 1.0,
 937.0: 1.0,
 938.0: 1.0,
 939.0: 1.0,
 940.0: 1.0,
 941.0: 1.0,
 942.0: 1.0,
 943.0: 1.0,
 944.0: 1.0,
 945.0: 1.0,
 ...}

In [27]:
data['DEPARTURE_DELAY']=data['DEPARTURE_DELAY'].map(dep_del_di)
data

         YEAR  MONTH  DAY  ...  WHEELS_OFF_HOUR  WHEELS_OFF_MINUTE  OUTCOME
985289   2019      2   17  ...               17                  1        0
5243685  2019      9    4  ...               11                 56        1
1604102  2019      3    3  ...               20                  3        1
3196153  2019      6   17  ...               17                 27        1
1910817  2019      4   10  ...                8                 48        1
...       ...    ...  ...  ...              ...                ...      ...
4985584  2019      9    3  ...                6                 50        0
4390712  2019      7   24  ...               12                 19        0
3684895  2019      7   19  ...               18                 50        0
560968   2019      1   22  ...                5                 55        0
1429176  2019      3    1  ...               15                 19        1

[5449996 rows x 59 columns]

In [28]:
cols=['YEAR','MONTH','DAY','DAY_OF_WEEK','ORIGIN_AIRPORT','DESTINATION_AIRPORT','DEPARTURE_DELAY','TAXI_OUT','SCHEDULED_TIME','DISTANCE','AIR_TIME','DIVERTED','AIR_SYSTEM_DELAY','SECURITY_DELAY','AIRLINE_DELAY','LATE_AIRCRAFT_DELAY','WEATHER_DELAY','AIRLINE_ORIGIN_AIRPORT','AIRLINE_DESTINATION_AIRPORT','ORIGIN_AIRPORT_DESTINATION_AIRPORT','9E','AA','AS','B6','DL','EV','F9','G4','HA','MQ','NK','OH','OO','UA','WN','YV','YX','DEPARTURE_TIME_HOUR','SCHEDULED_DEPARTURE_HOUR','SCHEDULED_ARRIVAL_HOUR','DEPARTURE_TIME_MINUTE','SCHEDULED_DEPARTURE_MINUTE','SCHEDULED_ARRIVAL_MINUTE','WHEELS_OFF_HOUR','WHEELS_OFF_MINUTE','AIR_SYSTEM_DELAY_is_missing','SECURITY_DELAY_is_missing','AIRLINE_DELAY_is_missing','LATE_AIRCRAFT_DELAY_is_missing','WEATHER_DELAY_is_missing']
Y_train=data['OUTCOME']
data=data[cols]
data

         YEAR  MONTH  ...  LATE_AIRCRAFT_DELAY_is_missing  WEATHER_DELAY_is_missing
985289   2019      2  ...                               1                         1
5243685  2019      9  ...                               0                         0
1604102  2019      3  ...                               1                         1
3196153  2019      6  ...                               0                         0
1910817  2019      4  ...                               1                         1
...       ...    ...  ...                             ...                       ...
4985584  2019      9  ...                               1                         1
4390712  2019      7  ...                               1                         1
3684895  2019      7  ...                               1                         1
560968   2019      1  ...                               1                         1
1429176  2019      3  ...                               0                         0

[5449996 rows x 50 columns]

In [29]:
df=pd.DataFrame(Y_train)
Y_train=df
Y_train

         OUTCOME
985289         0
5243685        1
1604102        1
3196153        1
1910817        1
...          ...
4985584        0
4390712        0
3684895        0
560968         0
1429176        1

[5449996 rows x 1 columns]

In [30]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=27, ratio=1.0)
smote_X_train, smote_Y_train = sm.fit_sample(data, Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)

In [31]:
cols=data.columns
X_train=pd.DataFrame(smote_X_train)
X_train.columns=cols
X_train

           YEAR  ...  WEATHER_DELAY_is_missing
0        2019.0  ...                  1.000000
1        2019.0  ...                  0.000000
2        2019.0  ...                  1.000000
3        2019.0  ...                  0.000000
4        2019.0  ...                  1.000000
...         ...  ...                       ...
7803243  2019.0  ...                  1.000000
7803244  2019.0  ...                  0.000000
7803245  2019.0  ...                  0.859023
7803246  2019.0  ...                  1.000000
7803247  2019.0  ...                  0.000000

[7803248 rows x 50 columns]

In [32]:
Y_train=smote_Y_train
Y_train=pd.DataFrame(Y_train)
Y_train.columns=['OUTCOME']
Y_train

         OUTCOME
0              0
1              1
2              1
3              1
4              1
...          ...
7803243        1
7803244        1
7803245        1
7803246        1
7803247        1

[7803248 rows x 1 columns]

In [0]:
data=X_test.join(Y_test)

In [35]:
data

         YEAR  MONTH  DAY  ...  WHEELS_OFF_HOUR WHEELS_OFF_MINUTE OUTCOME
3304404  2019      6   22  ...               10                 5       0
2908515  2019      5   31  ...               23                 1       1
6516946  2019     11   20  ...               18                11       0
2433078  2019      5   13  ...               12                12       0
5068670  2019      9    3  ...               16                33       0
...       ...    ...  ...  ...              ...               ...     ...
126518   2019      1   11  ...               14                27       0
7249509  2019     12   10  ...                9                15       0
2864023  2019      5   10  ...               19                11       1
6332609  2019     11   16  ...               11                43       0
5077878  2019      9    4  ...                7                 6       1

[1816666 rows x 59 columns]

In [36]:
cols=['YEAR','MONTH','DAY','DAY_OF_WEEK','ORIGIN_AIRPORT','DESTINATION_AIRPORT','DEPARTURE_DELAY','TAXI_OUT','SCHEDULED_TIME','DISTANCE','AIR_TIME','DIVERTED','AIR_SYSTEM_DELAY','SECURITY_DELAY','AIRLINE_DELAY','LATE_AIRCRAFT_DELAY','WEATHER_DELAY','AIRLINE_ORIGIN_AIRPORT','AIRLINE_DESTINATION_AIRPORT','ORIGIN_AIRPORT_DESTINATION_AIRPORT','9E','AA','AS','B6','DL','EV','F9','G4','HA','MQ','NK','OH','OO','UA','WN','YV','YX','DEPARTURE_TIME_HOUR','SCHEDULED_DEPARTURE_HOUR','SCHEDULED_ARRIVAL_HOUR','DEPARTURE_TIME_MINUTE','SCHEDULED_DEPARTURE_MINUTE','SCHEDULED_ARRIVAL_MINUTE','WHEELS_OFF_HOUR','WHEELS_OFF_MINUTE','AIR_SYSTEM_DELAY_is_missing','SECURITY_DELAY_is_missing','AIRLINE_DELAY_is_missing','LATE_AIRCRAFT_DELAY_is_missing','WEATHER_DELAY_is_missing','OUTCOME']
data=data[cols]
data

         YEAR  MONTH  ...  WEATHER_DELAY_is_missing  OUTCOME
3304404  2019      6  ...                         1        0
2908515  2019      5  ...                         1        1
6516946  2019     11  ...                         1        0
2433078  2019      5  ...                         1        0
5068670  2019      9  ...                         1        0
...       ...    ...  ...                       ...      ...
126518   2019      1  ...                         1        0
7249509  2019     12  ...                         1        0
2864023  2019      5  ...                         0        1
6332609  2019     11  ...                         1        0
5077878  2019      9  ...                         1        1

[1816666 rows x 51 columns]

In [37]:
data['ORIGIN_AIRPORT']=data['ORIGIN_AIRPORT'].map(ori_di)
data['DESTINATION_AIRPORT']=data['DESTINATION_AIRPORT'].map(des_di)
data

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

         YEAR  MONTH  ...  WEATHER_DELAY_is_missing  OUTCOME
3304404  2019      6  ...                         1        0
2908515  2019      5  ...                         1        1
6516946  2019     11  ...                         1        0
2433078  2019      5  ...                         1        0
5068670  2019      9  ...                         1        0
...       ...    ...  ...                       ...      ...
126518   2019      1  ...                         1        0
7249509  2019     12  ...                         1        0
2864023  2019      5  ...                         0        1
6332609  2019     11  ...                         1        0
5077878  2019      9  ...                         1        1

[1816666 rows x 51 columns]

In [38]:
data['DEPARTURE_DELAY']=data['DEPARTURE_DELAY'].map(dep_del_di)
data

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

         YEAR  MONTH  ...  WEATHER_DELAY_is_missing  OUTCOME
3304404  2019      6  ...                         1        0
2908515  2019      5  ...                         1        1
6516946  2019     11  ...                         1        0
2433078  2019      5  ...                         1        0
5068670  2019      9  ...                         1        0
...       ...    ...  ...                       ...      ...
126518   2019      1  ...                         1        0
7249509  2019     12  ...                         1        0
2864023  2019      5  ...                         0        1
6332609  2019     11  ...                         1        0
5077878  2019      9  ...                         1        1

[1816666 rows x 51 columns]

In [39]:
Y_test=data['OUTCOME']
data.drop(['OUTCOME'],axis=1,inplace=True)

data

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

         YEAR  MONTH  ...  LATE_AIRCRAFT_DELAY_is_missing  WEATHER_DELAY_is_missing
3304404  2019      6  ...                               1                         1
2908515  2019      5  ...                               1                         1
6516946  2019     11  ...                               1                         1
2433078  2019      5  ...                               1                         1
5068670  2019      9  ...                               1                         1
...       ...    ...  ...                             ...                       ...
126518   2019      1  ...                               1                         1
7249509  2019     12  ...                               1                         1
2864023  2019      5  ...                               0                         0
6332609  2019     11  ...                               1                         1
5077878  2019      9  ...                               1                         1

[1816666 rows x 50 columns]

In [40]:
data.dropna(inplace=True)

X_test=data
X_test

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

         YEAR  MONTH  ...  LATE_AIRCRAFT_DELAY_is_missing  WEATHER_DELAY_is_missing
3304404  2019      6  ...                               1                         1
2908515  2019      5  ...                               1                         1
6516946  2019     11  ...                               1                         1
2433078  2019      5  ...                               1                         1
5068670  2019      9  ...                               1                         1
...       ...    ...  ...                             ...                       ...
126518   2019      1  ...                               1                         1
7249509  2019     12  ...                               1                         1
2864023  2019      5  ...                               0                         0
6332609  2019     11  ...                               1                         1
5077878  2019      9  ...                               1                         1

[1816602 rows x 50 columns]

In [41]:
df=pd.DataFrame(Y_test)
Y_test=df
Y_test

         OUTCOME
3304404        0
2908515        1
6516946        0
2433078        0
5068670        0
...          ...
126518         0
7249509        0
2864023        1
6332609        0
5077878        1

[1816666 rows x 1 columns]

ADD ANY EXTRA FEATURE ENGINEERING HERE

In [0]:
from sklearn.utils import resample

# concatenate our training data back together
X = pd.concat([X_train, Y_train], axis=1)

# separate minority and majority classes
not_delay = X[X.OUTCOME==0]
delay = X[X.OUTCOME==1]

# upsample minority
delay_upsampled = resample(delay,
                          replace=True, # sample with replacement
                          n_samples=len(not_delay), # match number in majority class
                          random_state=27) # reproducible results

# combine majority and upsampled minority
upsampled = pd.concat([not_delay, delay_upsampled])

# check new class counts
print(upsampled["OUTCOME"].value_counts())

oversam_X_train=upsampled.drop("OUTCOME",axis=1)
oversam_Y_train=pd.DataFrame(upsampled.OUTCOME)

1    3027409
0    3027409
Name: OUTCOME, dtype: int64

In [0]:
for each in [oversam_Y_train,Y_test]:
    print(f"Outcome fraction = {each.OUTCOME.mean():.4f}")

Outcome fraction = 0.5000
Outcome fraction = 0.2936

In [0]:
train_data=oversam_X_train.join(oversam_Y_train)
test_data=X_test.join(Y_test)

In [42]:
for each in [Y_train,Y_test]:
    print(f"Outcome fraction = {each.OUTCOME.mean():.4f}")

Outcome fraction = 0.5000
Outcome fraction = 0.2844

In [0]:
train_data=X_train.join(Y_train)
test_data=X_test.join(Y_test)

In [44]:
train_data

           YEAR      MONTH  ...  WEATHER_DELAY_is_missing  OUTCOME
0        2019.0   2.000000  ...                  1.000000        0
1        2019.0   9.000000  ...                  0.000000        1
2        2019.0   3.000000  ...                  1.000000        1
3        2019.0   6.000000  ...                  0.000000        1
4        2019.0   4.000000  ...                  1.000000        1
...         ...        ...  ...                       ...      ...
7803243  2019.0  10.663059  ...                  1.000000        1
7803244  2019.0   9.000000  ...                  0.000000        1
7803245  2019.0   5.140977  ...                  0.859023        1
7803246  2019.0   1.000000  ...                  1.000000        1
7803247  2019.0   9.049170  ...                  0.000000        1

[7803248 rows x 51 columns]

In [45]:
test_data

         YEAR  MONTH  ...  WEATHER_DELAY_is_missing  OUTCOME
3304404  2019      6  ...                         1        0
2908515  2019      5  ...                         1        1
6516946  2019     11  ...                         1        0
2433078  2019      5  ...                         1        0
5068670  2019      9  ...                         1        0
...       ...    ...  ...                       ...      ...
126518   2019      1  ...                         1        0
7249509  2019     12  ...                         1        0
2864023  2019      5  ...                         0        1
6332609  2019     11  ...                         1        0
5077878  2019      9  ...                         1        1

[1816602 rows x 51 columns]

In [0]:
train_data.to_csv("train_data.csv",index=False)
test_data.to_csv("test_data.csv",index=False)

In [0]:
import json

with open('Origin_airport_dict_2019.json', 'w') as fp:
    json.dump(ori_di, fp)
with open('Destination_airport_dict_2019.json', 'w') as fp:
    json.dump(des_di, fp)
with open('Departure_delay_dict_2019.json', 'w') as fp:
    json.dump(dep_del_di, fp)

In [0]:
with open('Origin_airport_dict_2019.json', 'r') as fp:
    data = json.load(fp)
data

{'ABE': 0.2983783783783784,
 'ABI': 0.235686492495831,
 'ABQ': 0.2933410613086038,
 'ABR': 0.30570902394106814,
 'ABY': 0.2988668555240793,
 'ACK': 0.3053435114503817,
 'ACT': 0.23270440251572327,
 'ACV': 0.3190883190883191,
 'ACY': 0.3291272344900105,
 'ADK': 0.5652173913043478,
 'ADQ': 0.26857142857142857,
 'AEX': 0.30974155069582504,
 'AGS': 0.3328133125325013,
 'AKN': 0.3695652173913043,
 'ALB': 0.21415456518110498,
 'ALO': 0.21961620469083157,
 'AMA': 0.29571384520505706,
 'ANC': 0.2407580720636406,
 'APN': 0.22,
 'ASE': 0.3872901678657074,
 'ATL': 0.2546848502479902,
 'ATW': 0.31546300398759414,
 'AUS': 0.27950290510006454,
 'AVL': 0.28177295341474445,
 'AVP': 0.27624309392265195,
 'AZO': 0.23264137437365784,
 'BDL': 0.24257065325302798,
 'BET': 0.28191489361702127,
 'BFL': 0.25717063684978125,
 'BGM': 0.22083333333333333,
 'BGR': 0.24295774647887325,
 'BHM': 0.27185045242119915,
 'BIL': 0.1527114967462039,
 'BIS': 0.27795756921970516,
 'BJI': 0.2,
 'BLI': 0.22137404580152673,
 'BMI': 0.27157598499061913,
 'BNA': 0.2824224908039937,
 'BOI': 0.2764972108199137,
 'BOS': 0.2983153927088994,
 'BPT': 0.3651006711409396,
 'BQK': 0.27019498607242337,
 'BQN': 0.2775700934579439,
 'BRD': 0.27607361963190186,
 'BRO': 0.20948180815876516,
 'BRW': 0.2740740740740741,
 'BSM': 0.20164891789762968,
 'BTM': 0.10597302504816955,
 'BTR': 0.3517253459449991,
 'BTV': 0.2944760357432981,
 'BUF': 0.2312416752996892,
 'BUR': 0.24731819677525502,
 'BWI': 0.335455372222944,
 'BZN': 0.22815533980582525,
 'CAE': 0.29566488066244523,
 'CAK': 0.21365229944318417,
 'CDC': 0.23991507430997877,
 'CDV': 0.23954372623574144,
 'CEC': 0.34375,
 'CHA': 0.2955075845974329,
 'CHO': 0.2819918934568616,
 'CHS': 0.2566537939672268,
 'CID': 0.31227674374882497,
 'CIU': 0.32991803278688525,
 'CLD': 0.29324894514767935,
 'CLE': 0.25842251288149026,
 'CLL': 0.22494553376906318,
 'CLT': 0.3316516132207811,
 'CMH': 0.25922284886428315,
 'CMI': 0.24016938898971568,
 'CMX': 0.24848484848484848,
 'CNY': 0.03225806451612903,
 'COD': 0.39539347408829173,
 'COS': 0.2976862816542175,
 'COU': 0.30525272547076315,
 'CPR': 0.17885024840312277,
 'CRP': 0.28149920255183414,
 'CRW': 0.36769394261424015,
 'CSG': 0.2672018348623853,
 'CVG': 0.28687912361508777,
 'CWA': 0.23941068139963168,
 'DAB': 0.17857142857142858,
 'DAL': 0.35542739443872295,
 'DAY': 0.28189390618149934,
 'DBQ': 0.21557719054242003,
 'DCA': 0.27607653876219285,
 'DEN': 0.3312588099073701,
 'DFW': 0.31973068872614924,
 'DHN': 0.36967294350842417,
 'DIK': 0.1673469387755102,
 'DLG': 0.19298245614035087,
 'DLH': 0.35465529495380244,
 'DRO': 0.28681253696037845,
 'DSM': 0.2882621951219512,
 'DTW': 0.2688158554942298,
 'DVL': 0.2741514360313316,
 'EAU': 0.2882703777335984,
 'ECP': 0.1780380673499268,
 'EGE': 0.3244397011739594,
 'EKO': 0.16473317865429235,
 'ELM': 0.30787878787878786,
 'ELP': 0.2683156901792265,
 'ERI': 0.31551724137931036,
 'ESC': 0.1662971175166297,
 'EUG': 0.2451856946354883,
 'EVV': 0.29766536964980544,
 'EWN': 0.26652452025586354,
 'EWR': 0.3040507142504078,
 'EYW': 0.19284802043422733,
 'FAI': 0.2480225988700565,
 'FAR': 0.282242172104226,
 'FAT': 0.31763879128601546,
 'FAY': 0.27012383900928794,
 'FCA': 0.18871473354231974,
 'FLG': 0.33101314771848417,
 'FLL': 0.2766840082967799,
 'FNT': 0.19957424161788184,
 'FSD': 0.33046594982078853,
 'FSM': 0.26898326898326896,
 'FWA': 0.2913064361191162,
 'GCC': 0.1623296158612144,
 'GCK': 0.2892249527410208,
 'GEG': 0.24838667193467667,
 'GFK': 0.29276315789473684,
 'GGG': 0.3346534653465347,
 'GJT': 0.22283682338996444,
 'GNV': 0.32069288389513106,
 'GPT': 0.2297486033519553,
 'GRB': 0.26835641494643325,
 'GRI': 0.2254335260115607,
 'GRK': 0.2603869330796067,
 'GRR': 0.24548228115465853,
 'GSO': 0.28833652007648186,
 'GSP': 0.246368501529052,
 'GST': 0.5818181818181818,
 'GTF': 0.19216646266829865,
 'GTR': 0.29987129987129985,
 'GUC': 0.36065573770491804,
 'GUM': 0.26199261992619927,
 'HDN': 0.3142857142857143,
 'HIB': 0.22192866578599735,
 'HLN': 0.1663778162911612,
 'HNL': 0.2388808160241616,
 'HOB': 0.20185614849187936,
 'HOU': 0.33513539260282454,
 'HPN': 0.3557546053743451,
 'HRL': 0.20201207243460764,
 'HSV': 0.2402125279642058,
 'HYA': 0.2711864406779661,
 'HYS': 0.2826552462526767,
 'IAD': 0.2958876265834271,
 'IAG': 0.32209737827715357,
 'IAH': 0.32859177376148657,
 'ICT': 0.2833592534992224,
 'IDA': 0.18379888268156425,
 'ILG': 0.4864864864864865,
 'ILM': 0.22279459111397296,
 'IMT': 0.21095334685598377,
 'IND': 0.2519351540820797,
 'INL': 0.23318385650224216,
 'ISN': 0.24356435643564356,
 'ISP': 0.25464949928469244,
 'ITH': 0.42105263157894735,
 'ITO': 0.20563741191543883,
 'JAC': 0.23452157598499063,
 'JAN': 0.26440203116792155,
 'JAX': 0.25385144429160933,
 'JFK': 0.30846968238691047,
 'JLN': 0.3030888030888031,
 'JMS': 0.2633279483037157,
 'JNU': 0.3101379724055189,
 'KOA': 0.22179074669921225,
 'KTN': 0.2994652406417112,
 'LAN': 0.2848605577689243,
 'LAR': 0.18021978021978022,
 'LAS': 0.3188431152280805,
 'LAW': 0.2702970297029703,
 'LAX': 0.3280808312323325,
 'LBB': 0.26488985586075603,
 'LBE': 0.32841691248770893,
 'LCH': 0.20161834120026972,
 'LEX': 0.24132162275198663,
 'LFT': 0.30614250614250615,
 'LGA': 0.32635896906684553,
 'LGB': 0.2801528878822197,
 'LIH': 0.21988976193268442,
 'LIT': 0.2898688915375447,
 'LNK': 0.2730278696268304,
 'LRD': 0.23411562678878076,
 'LSE': 0.2146118721461187,
 'LWS': 0.10655737704918032,
 'MAF': 0.2716218530570303,
 'MBS': 0.2603150787696924,
 'MCI': 0.27028153658693005,
 'MCO': 0.2998865385263489,
 'MDT': 0.21102302755756888,
 'MDW': 0.32400228138054354,
 'MEI': 0.3062068965517241,
 'MEM': 0.26416353775552776,
 'MFE': 0.2125340599455041,
 'MFR': 0.232408325074331,
 'MGM': 0.32987312572087657,
 'MHK': 0.2524790236460717,
 'MHT': 0.22954091816367264,
 'MIA': 0.33077171688153123,
 'MKE': 0.2596719669462877,
 'MKG': 0.29750479846449135,
 'MLB': 0.1870967741935484,
 'MLI': 0.30217755443886096,
 'MLU': 0.30928270042194095,
 'MMH': 0.3181818181818182,
 'MOB': 0.3189937106918239,
 'MOT': 0.23825065274151436,
 'MQT': 0.28512396694214875,
 'MRY': 0.2864583333333333,
 'MSN': 0.2469579646017699,
 'MSO': 0.203125,
 'MSP': 0.2613973445418623,
 'MSY': 0.25769781881865944,
 'MTJ': 0.2665764546684709,
 'MVY': 0.3431952662721893,
 'MYR': 0.3144813593710373,
 'OAJ': 0.3116591928251121,
 'OAK': 0.33513213931509245,
 'OGG': 0.2707178993013732,
 'OKC': 0.26862805346443386,
 'OMA': 0.265557700876281,
 'OME': 0.41346153846153844,
 'ONT': 0.2688112660499793,
 'ORD': 0.3366036577343099,
 'ORF': 0.2595470990218411,
 'ORH': 0.2466281310211946,
 'OTH': 0.38461538461538464,
 'OTZ': 0.36072144288577157,
 'PAH': 0.22396856581532418,
 'PBG': 0.4372093023255814,
 'PBI': 0.3165379701127715,
 'PDX': 0.23120545236980386,
 'PHF': 0.3121902874132805,
 'PHL': 0.3113022113022113,
 'PHX': 0.311523042716615,
 'PIA': 0.2889189189189189,
 'PIB': 0.2869757174392936,
 'PIH': 0.2178030303030303,
 'PIT': 0.22384112827958105,
 'PLN': 0.22569444444444445,
 'PNS': 0.24339659557816473,
 'PPG': 0.6046511627906976,
 'PSC': 0.2210953346855984,
 'PSE': 0.20198675496688742,
 'PSG': 0.31273408239700373,
 'PSP': 0.29781573788854665,
 'PUB': 0.2639593908629442,
 'PVD': 0.2463460894789691,
 'PWM': 0.2641858010029031,
 'RAP': 0.2748447204968944,
 'RDD': 0.19285714285714287,
 'RDM': 0.20679723502304148,
 'RDU': 0.2765448557089084,
 'RHI': 0.4093333333333333,
 'RIC': 0.2819832851173256,
 'RKS': 0.1989247311827957,
 'RNO': 0.2895184135977337,
 'ROA': 0.2889733840304182,
 'ROC': 0.24335687857383115,
 'ROW': 0.28647925033467203,
 'RST': 0.2707558859975217,
 'RSW': 0.27351057457494354,
 'SAF': 0.3185840707964602,
 'SAN': 0.28212556972759073,
 'SAT': 0.24081326556120322,
 'SAV': 0.2821963394342762,
 'SBA': 0.2643773272652048,
 'SBN': 0.30859703164379726,
 'SBP': 0.28640386162510056,
 'SCC': 0.257396449704142,
 'SCE': 0.25977653631284914,
 'SDF': 0.2536760163103917,
 'SEA': 0.2987984508953692,
 'SFO': 0.30850832608841033,
 'SGF': 0.32246893460990017,
 'SGU': 0.22773623385452074,
 'SHV': 0.3017580144777663,
 'SIT': 0.2556317335945152,
 'SJC': 0.2986865205800117,
 'SJT': 0.24293785310734464,
 'SJU': 0.2696858425132599,
 'SLC': 0.2362028107614908,
 'SMF': 0.30428340960721695,
 'SMX': 0.2545454545454545,
 'SNA': 0.2569069019269676,
 'SPI': 0.25565081839438814,
 'SPS': 0.2505330490405117,
 'SRQ': 0.23228200371057514,
 'STC': 0.43859649122807015,
 'STL': 0.2874146960799873,
 'STT': 0.27327147560610593,
 'STX': 0.324,
 'SUN': 0.21469740634005763,
 'SUX': 0.2556237218813906,
 'SWF': 0.31095406360424027,
 'SYR': 0.23916887709991158,
 'TLH': 0.24140625,
 'TOL': 0.21370967741935484,
 'TPA': 0.273480338398872,
 'TRI': 0.244140625,
 'TTN': 0.33537921964050854,
 'TUL': 0.2636891469405985,
 'TUS': 0.24878290287977556,
 'TVC': 0.24297752808988765,
 'TWF': 0.1884272997032641,
 'TXK': 0.26594301221166894,
 'TYR': 0.27491785323110624,
 'TYS': 0.3178519593613933,
 'UST': 0.38524590163934425,
 'VEL': 0.06451612903225806,
 'VLD': 0.3063063063063063,
 'VPS': 0.25678119349005424,
 'WRG': 0.2907662082514735,
 'WYS': 0.1513157894736842,
 'XNA': 0.3363234703440889,
 'YAK': 0.1891385767790262,
 'YUM': 0.22889182058047494}

In [48]:
!ls

Departure_delay_dict_2019.json	    sample_data
Destination_airport_dict_2019.json  test_data.csv
drive				    train_data.csv
Origin_airport_dict_2019.json

In [49]:
# Import PyDrive and associated libraries.
# This only needs to be done once in a notebook.
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
# This only needs to be done once in a notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# Create & upload a text file.
uploaded = drive.CreateFile({'title': 'train_data_2019.csv'})
uploaded.SetContentFile("train_data.csv")
uploaded.Upload()
print('Uploaded file with ID {}'.format(uploaded.get('id')))

uploaded = drive.CreateFile({'title': 'test_data_2019.csv'})
uploaded.SetContentFile("test_data.csv")
uploaded.Upload()
print('Uploaded file with ID {}'.format(uploaded.get('id')))

Uploaded file with ID 1vvHcSKnjZMMqs4hxO3LwW9xKUmYW2swU
Uploaded file with ID 1TrGzIoNEzy5duatmiwlM7EESleMPYLP9

In [50]:
uploaded = drive.CreateFile({'title': 'Origin_airport_dict_2019.json'})
uploaded.SetContentFile("Origin_airport_dict_2019.json")
uploaded.Upload()
print('Uploaded file with ID {}'.format(uploaded.get('id')))

uploaded = drive.CreateFile({'title': 'Destination_airport_dict_2019.json'})
uploaded.SetContentFile("Destination_airport_dict_2019.json")
uploaded.Upload()
print('Uploaded file with ID {}'.format(uploaded.get('id')))

uploaded = drive.CreateFile({'title': 'Departure_delay_dict_2019.json'})
uploaded.SetContentFile("Departure_delay_dict_2019.json")
uploaded.Upload()
print('Uploaded file with ID {}'.format(uploaded.get('id')))

Uploaded file with ID 1RwRRK2HwRJScgXwvixfTVAabm55qXE8t
Uploaded file with ID 1BSQcafT30CtanALZs41LnBTWpUuM5css
Uploaded file with ID 1NE5qR8Rya9wesv8VVlPfL0uvQPopUdtI